In [1]:
import pandas as pd
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_row", 160)
pd.set_option('max_colwidth', 200)

In [2]:
a = pd.read_csv('accepted.csv')
a.head(3)

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68407277,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68355089,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.0,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68341763,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.0,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
a.shape

(2260701, 151)

In [5]:
#1. Remove all obserations with No Funded Amount First, How many:
print(len(a[a.funded_amnt.isnull()]))

33

In [6]:
drop = a[a.funded_amnt.isnull()].index
a.drop(drop, axis=0, inplace=True)
a.shape

(2260668, 151)

In [7]:
#No more NaN funded amounts: 
a[a.funded_amnt.isna()].shape

(0, 151)

In [8]:
#2. How many value types for "loan_status"?
print(a.loan_status.value_counts(dropna=False).sum()) #Total matches

a.loan_status.value_counts(dropna=False)

2260668

Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: loan_status, dtype: int64

In [9]:
#Create new column and map Charged Off = 0, Fully Paid = 1, Opposite from Imbalanced set because its evenly balanced. 
a['loan_status_bin'] = a['loan_status'].map({'Charged Off':0, 'Fully Paid':1})

In [10]:
#Quick Check:
a[['loan_status', 'loan_status_bin']].sample(10)

         loan_status  loan_status_bin
1538648      Current              NaN
1861906   Fully Paid              1.0
1718779   Fully Paid              1.0
832790       Current              NaN
1050490   Fully Paid              1.0
1314461  Charged Off              0.0
134740    Fully Paid              1.0
995124       Current              NaN
920999       Current              NaN
1892656  Charged Off              0.0

In [11]:
#Data Dictionary to review features: 
datadic = pd.read_excel('LCDataDictionary.xlsx')
datadic

,LoanStatNew,Description
0,acc_now_delinq,The number of accounts on which the borrower is now delinquent.
1,acc_open_past_24mths,Number of trades opened in past 24 months.
2,addr_state,The state provided by the borrower in the loan application
3,all_util,Balance to credit limit on all trades
4,annual_inc,The self-reported annual income provided by the borrower during registration.
5,annual_inc_joint,The combined self-reported annual income provided by the co-borrowers during registration
6,application_type,Indicates whether the loan is an individual application or a joint application with two co-borrowers
7,avg_cur_bal,Average current balance of all accounts
8,bc_open_to_buy,Total open to buy on revolving bankcards.
9,bc_util,Ratio of total current balance to high credit/credit limit for all bankcard accounts.
10,chargeoff_within_12_mths,Number of charge-offs within 12 months
11,collection_recovery_fee,post charge off collection fee
12,collections_12_mths_ex_med,Number of collections in 12 months excluding medical collections
13,delinq_2yrs,The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years
14,delinq_amnt,The past-due amount owed for the accounts on which the borrower is now delinquent.
15,desc,Loan description provided by the borrower
16,dti,"A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly inc..."
17,dti_joint,"A ratio calculated using the co-borrowers' total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the co-borrowers' combined self-reported ..."
18,earliest_cr_line,The month the borrower's earliest reported credit line was opened
19,emp_length,Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.
20,emp_title,The job title supplied by the Borrower when applying for the loan.*
21,fico_range_high,The upper boundary range the borrower’s FICO at loan origination belongs to.
22,fico_range_low,The lower boundary range the borrower’s FICO at loan origination belongs to.
23,funded_amnt,The total amount committed to that loan at that point in time.
24,funded_amnt_inv,The total amount committed by investors for that loan at that point in time.
25,grade,LC assigned loan grade
26,home_ownership,"The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER"
27,id,A unique LC assigned ID for the loan listing.
28,il_util,Ratio of total current balance to high credit/credit limit on all install acct
29,initial_list_status,"The initial listing status of the loan. Possible values are – W, F"
30,inq_fi,Number of personal finance inquiries
31,inq_last_12m,Number of credit inquiries in past 12 months
32,inq_last_6mths,The number of inquiries in past 6 months (excluding auto and mortgage inquiries)
33,installment,The monthly payment owed by the borrower if the loan originates.
34,int_rate,Interest Rate on the loan
35,issue_d,The month which the loan was funded
36,last_credit_pull_d,The most recent month LC pulled credit for this loan
37,last_fico_range_high,The upper boundary range the borrower’s last FICO pulled belongs to.
38,last_fico_range_low,The lower boundary range the borrower’s last FICO pulled belongs to.
39,last_pymnt_amnt,Last total payment amount received
40,last_pymnt_d,Last month payment was received
41,loan_amnt,"The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value."
42,loan_status,Current status of the loan
43,max_bal_bc,Maximum current balance owed on all revolving accounts
44,member_id,A unique LC assigned Id for the borrower member.
45,mo_sin_old_il_acct,Months since oldest bank installment account opened
46,mo_sin_old_rev_tl_op,Months since oldest revolving account opened
47,mo_sin_rcnt_rev_tl_op,Months since most recent revolving account opened
48,mo_sin_rcnt_tl,Months since most recent account opened
49,mort_acc,Number of mortgage accounts.
50,mths_since_last_delinq,The number of months since the borrower's last delinquency.
51,mths_since_last_major_derog,Months since most recent 90-day or worse rating
52,mths_since_last_record,The number of months since the last public record.
53,mths_since_rcnt_il,Months since most recent installment accounts opened
54,mths_since_recent_bc,Months since most recent bankcard account opened.
55,mths_since_recent_bc_dlq,Months since most recent bankcard delinquency
56,mths_since_recent_inq,Months since most recent inquiry.
57,mths_since_recent_revol_delinq,Months since most recent revolving delinquency.
58,next_pymnt_d,Next scheduled payment date
59,num_accts_ever_120_pd,Number of accounts ever 120 or more days past due
60,num_actv_bc_tl,Number of currently active bankcard accounts
61,num_actv_rev_tl,Number of currently active revolving trades
62,num_bc_sats,Number of satisfactory bankcard accounts
63,num_bc_tl,Number of bankcard accounts
64,num_il_tl,Number of installment accounts
65,num_op_rev_tl,Number of open revolving accounts
66,num_rev_accts,Number of revolving accounts
67,num_rev_tl_bal_gt_0,Number of revolving trades with balance >0
68,num_sats,Number of satisfactory accounts
69,num_tl_120dpd_2m,Number of accounts currently 120 days past due (updated in past 2 months)
70,num_tl_30dpd,Number of accounts currently 30 days past due (updated in past 2 months)
71,num_tl_90g_dpd_24m,Number of accounts 90 or more days past due in last 24 months
72,num_tl_op_past_12m,Number of accounts opened in past 12 months
73,open_acc,The number of open credit lines in the borrower's credit file.
74,open_acc_6m,Number of open trades in last 6 months
75,open_il_12m,Number of installment accounts opened in past 12 months
76,open_il_24m,Number of installment accounts opened in past 24 months
77,open_act_il,Number of currently active installment trades
78,open_rv_12m,Number of revolving trades opened in past 12 months
79,open_rv_24m,Number of revolving trades opened in past 24 months
80,out_prncp,Remaining outstanding principal for total amount funded
81,out_prncp_inv,Remaining outstanding principal for portion of total amount funded by investors
82,pct_tl_nvr_dlq,Percent of trades never delinquent
83,percent_bc_gt_75,Percentage of all bankcard accounts > 75% of limit.
84,policy_code,publicly available policy_code=1\nnew products not publicly available policy_code=2
85,pub_rec,Number of derogatory public records
86,pub_rec_bankruptcies,Number of public record bankruptcies
87,purpose,A category provided by the borrower for the loan request.
88,pymnt_plan,Indicates if a payment plan has been put in place for the loan
89,recoveries,post charge off gross recovery
90,revol_bal,Total credit revolving balance
91,revol_util,"Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit."
92,sub_grade,LC assigned loan subgrade
93,tax_liens,Number of tax liens
94,term,The number of payments on the loan. Values are in months and can be either 36 or 60.
95,title,The loan title provided by the borrower
96,tot_coll_amt,Total collection amounts ever owed
97,tot_cur_bal,Total current balance of all accounts
98,tot_hi_cred_lim,Total high credit/credit limit
99,total_acc,The total number of credit lines currently in the borrower's credit file
100,total_bal_ex_mort,Total credit balance excluding mortgage
101,total_bal_il,Total current balance of all installment accounts
102,total_bc_limit,Total bankcard high credit/credit limit
103,total_cu_tl,Number of finance trades
104,total_il_high_credit_limit,Total installment high credit/credit limit
105,total_pymnt,Payments received to date for total amount funded
106,total_pymnt_inv,Payments received to date for portion of total amount funded by investors
107,total_rec_int,Interest received to date
108,total_rec_late_fee,Late fees received to date
109,total_rec_prncp,Principal received to date
110,total_rev_hi_lim,Total revolving high credit/credit limit
111,url,URL for the LC page with listing data.
112,verification_status,"Indicates if income was verified by LC, not verified, or if the income source was verified"
113,verified_status_joint,"Indicates if the co-borrowers' joint income was verified by LC, not verified, or if the income source was verified"
114,zip_code,The first 3 numbers of the zip code provided by the borrower in the loan application.
115,revol_bal_joint,"Sum of revolving credit balance of the co-borrowers, net of duplicate balances"
116,sec_app_fico_range_low,FICO range (high) for the secondary applicant
117,sec_app_fico_range_high,FICO range (low) for the secondary applicant
118,sec_app_earliest_cr_line,Earliest credit line at time of application for the secondary applicant
119,sec_app_inq_last_6mths,Credit inquiries in the last 6 months at time of application for the secondary applicant
120,sec_app_mort_acc,Number of mortgage accounts at time of application for the secondary applicant
121,sec_app_open_acc,Number of open trades at time of application for the secondary applicant
122,sec_app_revol_util,Ratio of total current balance to high credit/credit limit for all revolving accounts
123,sec_app_open_act_il,Number of currently active installment trades at time of application for the secondary applicant
124,sec_app_num_rev_accts,Number of revolving accounts at time of application for the secondary applicant
125,sec_app_chargeoff_within_12_mths,Number of charge-offs within last 12 months at time of application for the secondary applicant
126,sec_app_collections_12_mths_ex_med,Number of collections within last 12 months excluding medical collections at time of application for the secondary applicant
127,sec_app_mths_since_last_major_derog,Months since most recent 90-day or worse rating at time of application for the secondary applicant
128,hardship_flag,Flags whether or not the borrower is on a hardship plan
129,hardship_type,Describes the hardship plan offering
130,hardship_reason,Describes the reason the hardship plan was offered
131,hardship_status,"Describes if the hardship plan is active, pending, canceled, completed, or broken"
132,deferral_term,Amount of months that the borrower is expected to pay less than the contractual monthly payment amount due to a hardship plan
133,hardship_amount,The interest payment that the borrower has committed to make each month while they are on a hardship plan
134,hardship_start_date,The start date of the hardship plan period
135,hardship_end_date,The end date of the hardship plan period
136,payment_plan_start_date,"The day the first hardship plan payment is due. For example, if a borrower has a hardship plan period of 3 months, the start date is the start of the three-month period in which the borrower is al..."
137,hardship_length,The number of months the borrower will make smaller payments than normally obligated due to a hardship plan
138,hardship_dpd,Account days past due as of the hardship plan start date
139,hardship_loan_status,Loan Status as of the hardship plan start date
140,orig_projected_additional_accrued_interest,The original projected additional interest amount that will accrue for the given hardship payment plan as of the Hardship Start Date. This field will be null if the borrower has broken their hards...
141,hardship_payoff_balance_amount,The payoff balance amount as of the hardship plan start date
142,hardship_last_payment_amount,The last payment amount as of the hardship plan start date
143,disbursement_method,"The method by which the borrower receives their loan. Possible values are: CASH, DIRECT_PAY"
144,debt_settlement_flag,"Flags whether or not the borrower, who has charged-off, is working with a debt-settlement company."
145,debt_settlement_flag_date,The most recent date that the Debt_Settlement_Flag has been set
146,settlement_status,"The status of the borrower’s settlement plan. Possible values are: COMPLETE, ACTIVE, BROKEN, CANCELLED, DENIED, DRAFT"
147,settlement_date,The date that the borrower agrees to the settlement plan
148,settlement_amount,The loan amount that the borrower has agreed to settle for
149,settlement_percentage,The settlement amount as a percentage of the payoff balance amount on the loan
150,settlement_term,The number of months that the borrower will be on the settlement plan
151,NaN,NaN
152,NaN,* Employer Title replaces Employer Name for all loans listed after 9/23/2013

In [12]:
#Reorder columns alphabetically to compare vs data dictionary
a.reindex(sorted(a.columns), axis=1).sample(5)

,acc_now_delinq,acc_open_past_24mths,addr_state,all_util,annual_inc,annual_inc_joint,application_type,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,collection_recovery_fee,collections_12_mths_ex_med,debt_settlement_flag,debt_settlement_flag_date,deferral_term,delinq_2yrs,delinq_amnt,desc,disbursement_method,dti,dti_joint,earliest_cr_line,emp_length,emp_title,fico_range_high,fico_range_low,funded_amnt,funded_amnt_inv,grade,hardship_amount,hardship_dpd,hardship_end_date,hardship_flag,hardship_last_payment_amount,hardship_length,hardship_loan_status,hardship_payoff_balance_amount,hardship_reason,hardship_start_date,hardship_status,hardship_type,home_ownership,id,il_util,initial_list_status,inq_fi,inq_last_12m,inq_last_6mths,installment,int_rate,issue_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,last_pymnt_amnt,last_pymnt_d,loan_amnt,loan_status,loan_status_bin,max_bal_bc,member_id,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_last_delinq,mths_since_last_major_derog,mths_since_last_record,mths_since_rcnt_il,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,next_pymnt_d,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,open_acc,open_acc_6m,open_act_il,open_il_12m,open_il_24m,open_rv_12m,open_rv_24m,orig_projected_additional_accrued_interest,out_prncp,out_prncp_inv,payment_plan_start_date,pct_tl_nvr_dlq,percent_bc_gt_75,policy_code,pub_rec,pub_rec_bankruptcies,purpose,pymnt_plan,recoveries,revol_bal,revol_bal_joint,revol_util,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_earliest_cr_line,sec_app_fico_range_high,sec_app_fico_range_low,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_mths_since_last_major_derog,sec_app_num_rev_accts,sec_app_open_acc,sec_app_open_act_il,sec_app_revol_util,settlement_amount,settlement_date,settlement_percentage,settlement_status,settlement_term,sub_grade,tax_liens,term,title,tot_coll_amt,tot_cur_bal,tot_hi_cred_lim,total_acc,total_bal_ex_mort,total_bal_il,total_bc_limit,total_cu_tl,total_il_high_credit_limit,total_pymnt,total_pymnt_inv,total_rec_int,total_rec_late_fee,total_rec_prncp,total_rev_hi_lim,url,verification_status,verification_status_joint,zip_code
1670282,0.0,2.0,HI,71.0,65000.0,NaN,Individual,6291.0,294.0,98.2,0.0,0.0,0.0,N,NaN,NaN,0.0,0.0,NaN,Cash,25.66,NaN,Sep-2000,9 years,General Manager,669.0,665.0,19200.0,19200.0,C,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RENT,99946631,61.0,w,1.0,1.0,0.0,665.49,14.99,Mar-2017,Mar-2019,679.0,675.0,665.49,Mar-2019,19200.0,Current,NaN,8392.0,NaN,140.0,198.0,23.0,11.0,0.0,NaN,NaN,98.0,11.0,23.0,NaN,11.0,NaN,Apr-2019,0.0,3.0,4.0,4.0,4.0,5.0,5.0,5.0,4.0,8.0,0.0,0.0,0.0,1.0,8.0,0.0,3.0,1.0,1.0,0.0,1.0,NaN,7383.42,7383.42,NaN,100.0,100.0,1.0,1.0,1.0,debt_consolidation,n,0.0,17456.0,NaN,94.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C4,0.0,36 months,Debt consolidation,0.0,44039.0,61886.0,10.0,44039.0,26583.0,15900.0,1.0,43486.0,15955.770000,15955.77,4139.19,0.0,11816.58,18400.0,https://lendingclub.com/browse/loanDetail.action?loan_id=99946631,Verified,NaN,968xx
7477,0.0,2.0,FL,57.0,65000.0,NaN,Individual,14298.0,5390.0,36.0,0.0,0.0,0.0,N,NaN,NaN,1.0,0.0,NaN,Cash,13.20,NaN,Jun-2001,NaN,NaN,664.0,660.0,10000.0,10000.0,B,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MORTGAGE,67929915,55.0,w,0.0,1.0,1.0,318.79,9.17,Dec-2015,Dec-2018,719.0,715.0,318.75,Jan-2019,10000.0,Fully Paid,1.0,937.0,NaN,174.0,170.0,1.0,1.0,3.0,22.0,26.0,68.0,35.0,35.0,22.0,1.0,22.0,NaN,2.0,5.0,7.0,5.0,5.0,9.0,7.0,14.0,7.0,9.0,0.0,0.0,0.0,1.0,9.0,1.0,1.0,0.0,0.0,1.0,2.0,NaN,0.00,0.00,NaN,80.0,20.0,1.0,1.0,0.0,debt_consolidation,n,0.0,8548.0,NaN,59.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B2,1.0,36 months,Debt consolidation,0.0,128681.0,153172.0,26.0,21027.0,12479.0,8000.0,0.0,22572.0,11464.953562,11464.95,1464.95,0.0,10000.00,15300.0,https://lendingclub.com/browse/loanDetail.action?loan_id=67929915,Verified,NaN,339xx
613602,0.0,6.0,MA,30.0,63000.0,NaN,Individual,19850.0,29757.0,18.0,0.0,0.0,0.0,N,NaN,NaN,0.0,0.0,NaN,Cash,9.49,NaN,Aug-1997,10+ years,Project Management,729.0,725.0,12000.0,12000.0,B,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MORTGAGE,112756793,71.0,w,0.0,0.0,0.0,254.56,9.93,Jul-2017,Aug-2018,724.0,720.0,10151.94,Aug-2018,12000.0,Fully Paid,1.0,4585.0,NaN,128.0,239.0,7.0,7.0,4.0,64.0,64.0,NaN,21.0,7.0,NaN,23.0,NaN,NaN,2.0,4.0,6.0,7.0,11.0,9.0,13.0,19.0,6.0,15.0,0.0,0.0,0.0,2.0,15.0,0.0,1.0,0.0,1.0,2.0,3.0,NaN,0.00,0.00,NaN,93.8,14.3,1.0,0.0,0.0,debt_consolidation,n,0.0,7411.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B2,0.0,60 months,Debt consolidation,75.0,277893.0,332495.0,32.0,20282.0,12871.0,36300.0,3.0,18086.0,13193.416323,13193.42,1193.42,0.0,12000.00,49300.0,https://lendingclub.com/browse/loanDetail.action?loan_id=112756793,Source Verified,NaN,026xx
113279,0.0,3.0,CT,NaN,65000.0,NaN,Individual,7472.0,1602.0,70.9,0.0,0.0,0.0,N,NaN,NaN,0.0,0.0,NaN,Cash,14.07,NaN,Feb-2003,NaN,NaN,669.0,665.0,12000.0,12000.0,C,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MORTGAGE,61342950,NaN,f,NaN,NaN,2.0,268.70,12.29,Oct-2015,Mar-2019,589.0,585.0,268.70,Mar-2019,12000.0,Current,NaN,NaN,NaN,12.0,152.0,3.0,3.0,1.0,70.0,70.0,61.0,NaN,26.0,70.0,1.0,70.0,Apr-2019,3.0,2.0,4.0,2.0,7.0,1.0,6.0,12.0,4.0,9.0,0.0,0.0,0.0,3.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4619.65,4619.65,NaN,78.6,50.0,1.0,2.0,0.0,debt_consolidation,n,0.0,5446.0,NaN,36.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C1,1.0,60 months,Debt consolidation,7470.0,59779.0,111374.0,15.0,21422.0,NaN,5500.0,NaN,20784.0,10996.220000,10996.22,3615.87,0.0,7380.35,14800.0,https://lendingclub.com/browse/loanDetail.action?loan_id=61342950,Not Verified,NaN,060xx
994403,0.0,6.0,CA,43.0,30000.0,NaN,Individual,1270.0,440.0,92.1,0.0,0.0,0.0,N,NaN,NaN,0.0,0.0,NaN,Cash,11.08,NaN,Oct-1987,NaN,NaN,674.0,670.0,10000.0,10000.0,C,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RENT,75407332,88.0,w,0.0,2.0,2.0,344.02,14.46,Mar-2016,Nov-2017,684.0,680.0,5324.90,Dec-2017,10000.0,Fully Paid,1.0,2772.0,NaN,129.0,341.0,5.0,5.0,3.0,NaN,NaN,60.0,14.0,14.0,NaN,0.0,NaN,NaN,0.0,2.0,4.0,2.0,10.0,4.0,9.0,25.0,4.0,10.0,0.0,0.0,0.0,1.0,10.0,1.0,1.0,0.0,2.0,1.0,4.0,NaN,0.00,0.00,NaN,96.4,100.0,1.0,1.0,1.0,debt_consolidation,n,0.0,5945.0,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C4,0.0,36 months,Debt consolidation,0.0,11428.0,26749.0,33.0,11428.0,5483.0,5600.0,6.0,6249.0,11853.251200,11853.25,1853.25,0.0,10000.00,20500.0,https://lendingclub.com/browse/loanDetail.action?loan_id=75407332,Verified,NaN,958xx

In [13]:
#5a. Starting Point of (entire) Dataframe of accepted loans: 
a.shape

(2260668, 152)

In [14]:
a.head(2)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68407277,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68355089,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.0,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [15]:
#5b. We will ONLY use loan_status_bin = 1 (Charged Off / Defaulted), or 0 (Paid In Full)

In [16]:
a.loan_status_bin.value_counts(dropna=False)

1.0    1076751
NaN     915358
0.0     268559
Name: loan_status_bin, dtype: int64

In [17]:
df = a[~a.loan_status_bin.isna()].reset_index(drop=True)
df.shape

(1345310, 152)

In [18]:
df.head(2)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68407277,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68355089,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.0,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [19]:
#5c. Let's drop 5 obvious columns that won't help - 'loan_status', 'url', 'zip_code', 'id', 'member_id'
df = df.drop(['loan_status', 'url', 'zip_code', 'id', 'member_id'], axis=1)
df

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,desc,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,n,NaN,debt_consolidation,Debt consolidation,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,n,NaN,small_business,Business,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,n,NaN,home_improvement,NaN,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,n,NaN,major_purchase,Major purchase,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.0,0.0,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,11950.0,11950.0,11950.0,36 months,13.44,405.18,C,C3,Veterinary Tecnician,4 years,RENT,34000.0,Source Verified,Dec-2015,n,NaN,debt_consolidation,Debt consolidation,GA,10.20,0.0,Oct-1987,690.0,694.0,0.0,NaN,NaN,5.0,0.0,8822.0,68.4,6.0,w,0.0,0.0,13708.948530,13708.95,11950.00,1758.95,0.0,0.0,0.0,May-2017,7653.56,NaN,May-2017,759.0,755.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,12798.0,0.0,1.0,0.0,0.0,338.0,3976.0,99.0,0.0,0.0,4522.0,76.0,12900.0,0.0,0.0,0.0,0.0,2560.0,844.0,91.0,0.0,0.0,338.0,54.0,32.0,32.0,0.0,36.0,NaN,NaN,NaN,0.0,2.0,3.0,2.0,2.0,2.0,4.0,4.0,3.0,5.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,16900.0,12798.0,9400.0,4000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345305,18000.0,18000.0,18000.0,60 months,9.49,377.95,B,B2,NaN,5 years,OWN,130000.0,Not Verified,Oct-2016,n,NaN,home_improvement,Home improvement,TX,20.59,0.0,Jul-2004,735.0,739.0,1.0,NaN,NaN,17.0,0.0,23833.0,34.0,39.0,f,0.0,0.0,20756.233632,20756.23,18000.00,2756.23,0.0,0.0,0.0,Aug-2018,12828.77,NaN,Mar-2019,709.0,705.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,168758.0,0.0,6.0,0.0,3.0,15.0,30516.0,52.0,0.0,3.0,7061.0,41.0,70100.0,1.0,2.0,1.0,6.0,9927.0,4161.0,68.2,0.0,0.0,113.0,146.0,17.0,15.0,3.0,17.0,NaN,2.0,NaN,0.0,3.0,9.0,3.0,5.0,21.0,10.0,15.0,9.0,17.0,0.0,0.0,0.0,0.0,100.0,33.3,0.0,0.0,275356.0,54349.0,13100.0,77756.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345306,29400.0,29400.0,29400.0,60 months,13.99,683.94,C,C3,Chief Operating Officer,9 years,MORTGAGE,180792.0,Not Verified,Oct-2016,n,NaN,debt_consolidation,Debt consolidation,CA,22.03,0.0,Mar-2002,705.0,709.0,1.0,NaN,NaN,16.0,0.0,77480.0,85.2,32.0,f,0.0,0.0,35848.764532,35848.76,29400.00,6448.76,0.0,0.0,0.0,Jul-2018,22192.81,NaN,Jul-2018,719.0,715.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,663465.0,0.0,4.0,2.0,4.0,8.0,70652.0,50.0,0.0,0.0,31069.0,68.0,86500.0,3.0,0.0,2.0,4.0,44231.0,8427.0,69.4,0.0,0.0,145.0,174.0,31.0,8.0,3.0,70.0,NaN,3.0,NaN,0.0,4.0,5.0,7.0,9.0,17.0,8.0,10.0,5.0,16.0,0.0,0.0,0.0,2.0,100.0,42.9,0.0,0.0,719056.0,148305.0,56500.0,95702.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345307,32000.0,32000.0,32000.0,60 months,14.49,752.74,C,C4,Sales Manager,3 years,MORTGAGE,157000.0,Source Verified,Oct-2016,n,NaN,home_improvement,Home improvement,AZ,10.34,0.0,Jun-2011,735.0,739.0,0.0,NaN,NaN,14.0,0.0,111598.0,27.4,18.0,f,0.0,0.0,3737.940000,3737.94,1876.47,1861.47,0.0,0.0,0.0,Mar-2017,752.74,NaN,Dec-2018,499.0,0.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,408701.0,2.0,2.0,0.0,2.0,16.0,11274.0,47.0,2.0,7.0,736.0,36.0,207500.0,2.0,2.0,0.0,10.0,29193.0,14118.0,10.6,0.0,0.0,53.0,63.0,4.0,4.0,3.0,4.0,NaN,15.0,NaN,0.0,5.0,8.0,7.0,7.0,4.0,11.0,11.0,8.0,14.0,0.0,0.0,0.0,2.0,100.0,0.0,0.0,0.0,524379.0,122872.0,15800.0,23879.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1345308,16000.0,16000.0,16000.0,60 months,12.79,362.34,C,C1,Manager,10+ years,RENT,150000.0,Not Verified,Oct-2016,n,NaN,medical,Medical expenses,NC,12.25,0.0,Aug-1997,665.0,669.0,0.0,68.0,26.0,12.0,4.0,7700.0,55.0,28.0,f,0.0,0.0,18660.607569,18660.61,16000.00,2660.61,0.0,0.0,0.0,Mar-2018,12874.54,NaN,Mar-2019,684.0,680.0,0.0,68.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,65797.0,1.0,5.0,2.0,6.0,4.0,58097.0,79.0,0.0,3.0,4516.0,75.0,14000.0,1.0,1.0,1.0,9.0,5982.0,2720.0,73.1,0.0,0.0,147.0,229.0,17.0,4.0,0.0,17.0,NaN,12.0,NaN,1.0,3.0,4.0,4.0,5.0,15.0,6.0,11.0,4.0,12.0,0.0,0.0,0.0,2.0,92.0,50.0,3.0,0.0,87473.0,65797.0,10100.0,73473.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345309,24000.0,24000.0,24000.0,60 months,14.49,564.56,C,C4,Program Manager,6 years,RENT,110000.0,Not Verified,Oct-2016,n,NaN,debt_consolidation,Debt consolidation,FL,18.30,0.0,Jul-1999,660.0,664.0,0.0,67.0,72.0,10.0,1.0,17641.0,68.1,31.0,f,0.0,0.0,6755.400000,6755.40,3521.91,3233.49,0.0,0.0,0.0,Oct-2017,564.56,NaN,Mar-2019,594.0,590.0,0.0,67.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,62426.0,0.0,2.0,0.0,2.0,20.0,44785.0,78.0,1.0,5.0,6172.0,73.0,25900.0,0.0,0.0,1.0,7.0,6243.0,4660.0,77.5,0.0,0.0,132.0,206.0,9.0,9.0,2.0,9.0,NaN,9.0,NaN,1.0,5.0,7.0,5.0,15.0,4.0,8.0,24.0,7.0,10.0,0.0,0.0,0.0,1.0,96.2,40.0,1.0,0.0,84664.0,62426.0,20700.0,58764.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,Y,Mar-2019,ACTIVE,Mar-2019,10000.0,44.82,1.0,0.0

In [20]:
#5d. At time of application, we only know "loan_amnt", we do not know "funded_amnt" or "funded_amnt_inv". 
#5d. Drop 2 more columns, "funded_amnt" and "funded_amnt_inv".

In [21]:
df = df.drop(['funded_amnt', 'funded_amnt_inv'], axis=1)
df

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,desc,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,n,NaN,debt_consolidation,Debt consolidation,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,n,NaN,small_business,Business,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,n,NaN,home_improvement,NaN,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,n,NaN,major_purchase,Major purchase,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.0,0.0,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,11950.0,36 months,13.44,405.18,C,C3,Veterinary Tecnician,4 years,RENT,34000.0,Source Verified,Dec-2015,n,NaN,debt_consolidation,Debt consolidation,GA,10.20,0.0,Oct-1987,690.0,694.0,0.0,NaN,NaN,5.0,0.0,8822.0,68.4,6.0,w,0.0,0.0,13708.948530,13708.95,11950.00,1758.95,0.0,0.0,0.0,May-2017,7653.56,NaN,May-2017,759.0,755.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,12798.0,0.0,1.0,0.0,0.0,338.0,3976.0,99.0,0.0,0.0,4522.0,76.0,12900.0,0.0,0.0,0.0,0.0,2560.0,844.0,91.0,0.0,0.0,338.0,54.0,32.0,32.0,0.0,36.0,NaN,NaN,NaN,0.0,2.0,3.0,2.0,2.0,2.0,4.0,4.0,3.0,5.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,16900.0,12798.0,9400.0,4000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345305,18000.0,60 months,9.49,377.95,B,B2,NaN,5 years,OWN,130000.0,Not Verified,Oct-2016,n,NaN,home_improvement,Home improvement,TX,20.59,0.0,Jul-2004,735.0,739.0,1.0,NaN,NaN,17.0,0.0,23833.0,34.0,39.0,f,0.0,0.0,20756.233632,20756.23,18000.00,2756.23,0.0,0.0,0.0,Aug-2018,12828.77,NaN,Mar-2019,709.0,705.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,168758.0,0.0,6.0,0.0,3.0,15.0,30516.0,52.0,0.0,3.0,7061.0,41.0,70100.0,1.0,2.0,1.0,6.0,9927.0,4161.0,68.2,0.0,0.0,113.0,146.0,17.0,15.0,3.0,17.0,NaN,2.0,NaN,0.0,3.0,9.0,3.0,5.0,21.0,10.0,15.0,9.0,17.0,0.0,0.0,0.0,0.0,100.0,33.3,0.0,0.0,275356.0,54349.0,13100.0,77756.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345306,29400.0,60 months,13.99,683.94,C,C3,Chief Operating Officer,9 years,MORTGAGE,180792.0,Not Verified,Oct-2016,n,NaN,debt_consolidation,Debt consolidation,CA,22.03,0.0,Mar-2002,705.0,709.0,1.0,NaN,NaN,16.0,0.0,77480.0,85.2,32.0,f,0.0,0.0,35848.764532,35848.76,29400.00,6448.76,0.0,0.0,0.0,Jul-2018,22192.81,NaN,Jul-2018,719.0,715.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,663465.0,0.0,4.0,2.0,4.0,8.0,70652.0,50.0,0.0,0.0,31069.0,68.0,86500.0,3.0,0.0,2.0,4.0,44231.0,8427.0,69.4,0.0,0.0,145.0,174.0,31.0,8.0,3.0,70.0,NaN,3.0,NaN,0.0,4.0,5.0,7.0,9.0,17.0,8.0,10.0,5.0,16.0,0.0,0.0,0.0,2.0,100.0,42.9,0.0,0.0,719056.0,148305.0,56500.0,95702.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345307,32000.0,60 months,14.49,752.74,C,C4,Sales Manager,3 years,MORTGAGE,157000.0,Source Verified,Oct-2016,n,NaN,home_improvement,Home improvement,AZ,10.34,0.0,Jun-2011,735.0,739.0,0.0,NaN,NaN,14.0,0.0,111598.0,27.4,18.0,f,0.0,0.0,3737.940000,3737.94,1876.47,1861.47,0.0,0.0,0.0,Mar-2017,752.74,NaN,Dec-2018,499.0,0.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,408701.0,2.0,2.0,0.0,2.0,16.0,11274.0,47.0,2.0,7.0,736.0,36.0,207500.0,2.0,2.0,0.0,10.0,29193.0,14118.0,10.6,0.0,0.0,53.0,63.0,4.0,4.0,3.0,4.0,NaN,15.0,NaN,0.0,5.0,8.0,7.0,7.0,4.0,11.0,11.0,8.0,14.0,0.0,0.0,0.0,2.0,100.0,0.0,0.0,0.0,524379.0,122872.0,15800.0,23879.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1345308,16000.0,60 months,12.79,362.34,C,C1,Manager,10+ years,RENT,150000.0,Not Verified,Oct-2016,n,NaN,medical,Medical expenses,NC,12.25,0.0,Aug-1997,665.0,669.0,0.0,68.0,26.0,12.0,4.0,7700.0,55.0,28.0,f,0.0,0.0,18660.607569,18660.61,16000.00,2660.61,0.0,0.0,0.0,Mar-2018,12874.54,NaN,Mar-2019,684.0,680.0,0.0,68.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,65797.0,1.0,5.0,2.0,6.0,4.0,58097.0,79.0,0.0,3.0,4516.0,75.0,14000.0,1.0,1.0,1.0,9.0,5982.0,2720.0,73.1,0.0,0.0,147.0,229.0,17.0,4.0,0.0,17.0,NaN,12.0,NaN,1.0,3.0,4.0,4.0,5.0,15.0,6.0,11.0,4.0,12.0,0.0,0.0,0.0,2.0,92.0,50.0,3.0,0.0,87473.0,65797.0,10100.0,73473.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345309,24000.0,60 months,14.49,564.56,C,C4,Program Manager,6 years,RENT,110000.0,Not Verified,Oct-2016,n,NaN,debt_consolidation,Debt consolidation,FL,18.30,0.0,Jul-1999,660.0,664.0,0.0,67.0,72.0,10.0,1.0,17641.0,68.1,31.0,f,0.0,0.0,6755.400000,6755.40,3521.91,3233.49,0.0,0.0,0.0,Oct-2017,564.56,NaN,Mar-2019,594.0,590.0,0.0,67.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,62426.0,0.0,2.0,0.0,2.0,20.0,44785.0,78.0,1.0,5.0,6172.0,73.0,25900.0,0.0,0.0,1.0,7.0,6243.0,4660.0,77.5,0.0,0.0,132.0,206.0,9.0,9.0,2.0,9.0,NaN,9.0,NaN,1.0,5.0,7.0,5.0,15.0,4.0,8.0,24.0,7.0,10.0,0.0,0.0,0.0,1.0,96.2,40.0,1.0,0.0,84664.0,62426.0,20700.0,58764.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,Y,Mar-2019,ACTIVE,Mar-2019,10000.0,44.82,1.0,0.0

In [28]:
#5e. All the remaining loans do NOT have payment plan....let's drop it. 
df.pymnt_plan.value_counts()

n    1345310
Name: pymnt_plan, dtype: int64

In [29]:
df = df.drop(['pymnt_plan'], axis=1)
df

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,desc,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,NaN,debt_consolidation,Debt consolidation,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,NaN,small_business,Business,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,NaN,home_improvement,NaN,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,NaN,major_purchase,Major purchase,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.0,0.0,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,11950.0,36 months,13.44,405.18,C,C3,Veterinary Tecnician,4 years,RENT,34000.0,Source Verified,Dec-2015,NaN,debt_consolidation,Debt consolidation,GA,10.20,0.0,Oct-1987,690.0,694.0,0.0,NaN,NaN,5.0,0.0,8822.0,68.4,6.0,w,0.0,0.0,13708.948530,13708.95,11950.00,1758.95,0.0,0.0,0.0,May-2017,7653.56,NaN,May-2017,759.0,755.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,12798.0,0.0,1.0,0.0,0.0,338.0,3976.0,99.0,0.0,0.0,4522.0,76.0,12900.0,0.0,0.0,0.0,0.0,2560.0,844.0,91.0,0.0,0.0,338.0,54.0,32.0,32.0,0.0,36.0,NaN,NaN,NaN,0.0,2.0,3.0,2.0,2.0,2.0,4.0,4.0,3.0,5.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,0.0,16900.0,12798.0,9400.0,4000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345305,18000.0,60 months,9.49,377.95,B,B2,NaN,5 years,OWN,130000.0,Not Verified,Oct-2016,NaN,home_improvement,Home improvement,TX,20.59,0.0,Jul-2004,735.0,739.0,1.0,NaN,NaN,17.0,0.0,23833.0,34.0,39.0,f,0.0,0.0,20756.233632,20756.23,18000.00,2756.23,0.0,0.0,0.0,Aug-2018,12828.77,NaN,Mar-2019,709.0,705.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,168758.0,0.0,6.0,0.0,3.0,15.0,30516.0,52.0,0.0,3.0,7061.0,41.0,70100.0,1.0,2.0,1.0,6.0,9927.0,4161.0,68.2,0.0,0.0,113.0,146.0,17.0,15.0,3.0,17.0,NaN,2.0,NaN,0.0,3.0,9.0,3.0,5.0,21.0,10.0,15.0,9.0,17.0,0.0,0.0,0.0,0.0,100.0,33.3,0.0,0.0,275356.0,54349.0,13100.0,77756.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345306,29400.0,60 months,13.99,683.94,C,C3,Chief Operating Officer,9 years,MORTGAGE,180792.0,Not Verified,Oct-2016,NaN,debt_consolidation,Debt consolidation,CA,22.03,0.0,Mar-2002,705.0,709.0,1.0,NaN,NaN,16.0,0.0,77480.0,85.2,32.0,f,0.0,0.0,35848.764532,35848.76,29400.00,6448.76,0.0,0.0,0.0,Jul-2018,22192.81,NaN,Jul-2018,719.0,715.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,663465.0,0.0,4.0,2.0,4.0,8.0,70652.0,50.0,0.0,0.0,31069.0,68.0,86500.0,3.0,0.0,2.0,4.0,44231.0,8427.0,69.4,0.0,0.0,145.0,174.0,31.0,8.0,3.0,70.0,NaN,3.0,NaN,0.0,4.0,5.0,7.0,9.0,17.0,8.0,10.0,5.0,16.0,0.0,0.0,0.0,2.0,100.0,42.9,0.0,0.0,719056.0,148305.0,56500.0,95702.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345307,32000.0,60 months,14.49,752.74,C,C4,Sales Manager,3 years,MORTGAGE,157000.0,Source Verified,Oct-2016,NaN,home_improvement,Home improvement,AZ,10.34,0.0,Jun-2011,735.0,739.0,0.0,NaN,NaN,14.0,0.0,111598.0,27.4,18.0,f,0.0,0.0,3737.940000,3737.94,1876.47,1861.47,0.0,0.0,0.0,Mar-2017,752.74,NaN,Dec-2018,499.0,0.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,408701.0,2.0,2.0,0.0,2.0,16.0,11274.0,47.0,2.0,7.0,736.0,36.0,207500.0,2.0,2.0,0.0,10.0,29193.0,14118.0,10.6,0.0,0.0,53.0,63.0,4.0,4.0,3.0,4.0,NaN,15.0,NaN,0.0,5.0,8.0,7.0,7.0,4.0,11.0,11.0,8.0,14.0,0.0,0.0,0.0,2.0,100.0,0.0,0.0,0.0,524379.0,122872.0,15800.0,23879.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1345308,16000.0,60 months,12.79,362.34,C,C1,Manager,10+ years,RENT,150000.0,Not Verified,Oct-2016,NaN,medical,Medical expenses,NC,12.25,0.0,Aug-1997,665.0,669.0,0.0,68.0,26.0,12.0,4.0,7700.0,55.0,28.0,f,0.0,0.0,18660.607569,18660.61,16000.00,2660.61,0.0,0.0,0.0,Mar-2018,12874.54,NaN,Mar-2019,684.0,680.0,0.0,68.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,65797.0,1.0,5.0,2.0,6.0,4.0,58097.0,79.0,0.0,3.0,4516.0,75.0,14000.0,1.0,1.0,1.0,9.0,5982.0,2720.0,73.1,0.0,0.0,147.0,229.0,17.0,4.0,0.0,17.0,NaN,12.0,NaN,1.0,3.0,4.0,4.0,5.0,15.0,6.0,11.0,4.0,12.0,0.0,0.0,0.0,2.0,92.0,50.0,3.0,0.0,87473.0,65797.0,10100.0,73473.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1345309,24000.0,60 months,14.49,564.56,C,C4,Program Manager,6 years,RENT,110000.0,Not Verified,Oct-2016,NaN,debt_consolidation,Debt consolidation,FL,18.30,0.0,Jul-1999,660.0,664.0,0.0,67.0,72.0,10.0,1.0,17641.0,68.1,31.0,f,0.0,0.0,6755.400000,6755.40,3521.91,3233.49,0.0,0.0,0.0,Oct-2017,564.56,NaN,Mar-2019,594.0,590.0,0.0,67.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,62426.0,0.0,2.0,0.0,2.0,20.0,44785.0,78.0,1.0,5.0,6172.0,73.0,25900.0,0.0,0.0,1.0,7.0,6243.0,4660.0,77.5,0.0,0.0,132.0,206.0,9.0,9.0,2.0,9.0,NaN,9.0,NaN,1.0,5.0,7.0,5.0,15.0,4.0,8.0,24.0,7.0,10.0,0.0,0.0,0.0,1.0,96.2,40.0,1.0,0.0,84664.0,62426.0,20700.0,58764.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,Y,Mar-2019,ACTIVE,Mar-2019,10000.0,44.82,1.0,0.0

In [22]:
#6. Extract all loans with grade "G" (riskiest):
G = df[df.grade=="G"]
G

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,desc,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
305,30000.0,60 months,27.49,924.87,G,G2,Service Technian Lead,1 year,MORTGAGE,115000.0,Verified,Dec-2015,n,NaN,other,Other,CO,17.73,0.0,Oct-2001,675.0,679.0,2.0,NaN,NaN,14.0,0.0,50634.0,58.7,20.0,w,0.0,0.0,13015.230000,13015.23,2934.76,7124.27,0.0,2956.20,532.1160,Dec-2016,924.87,NaN,Jun-2017,534.0,530.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,300130.0,3.0,3.0,2.0,3.0,1.0,20011.0,82.0,4.0,6.0,21644.0,64.0,86200.0,3.0,1.0,7.0,9.0,23087.0,31947.0,54.5,0.0,0.0,58.0,170.0,6.0,1.0,4.0,7.0,NaN,1.0,NaN,0.0,5.0,6.0,7.0,8.0,4.0,10.0,12.0,6.0,14.0,0.0,0.0,0.0,6.0,100.0,28.6,0.0,0.0,348717.0,70645.0,70200.0,24517.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
337,19225.0,60 months,26.99,586.93,G,G1,OTR Truck Driver,< 1 year,MORTGAGE,56600.0,Verified,Dec-2015,n,NaN,debt_consolidation,NaN,OH,18.21,0.0,Apr-1990,710.0,714.0,1.0,51.0,28.0,8.0,1.0,7055.0,44.7,22.0,w,0.0,0.0,14014.250000,14014.25,4846.64,9167.61,0.0,0.00,0.0000,Jan-2018,586.93,NaN,Mar-2019,499.0,0.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,125.0,33946.0,5.0,3.0,3.0,3.0,3.0,26891.0,93.0,2.0,2.0,605.0,76.0,15800.0,2.0,4.0,5.0,5.0,4243.0,5847.0,12.7,0.0,0.0,122.0,308.0,2.0,2.0,0.0,2.0,NaN,0.0,51.0,0.0,2.0,4.0,3.0,5.0,10.0,5.0,12.0,4.0,8.0,0.0,0.0,0.0,5.0,90.5,33.3,0.0,1.0,44633.0,33946.0,6700.0,28833.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
701,17125.0,60 months,27.99,533.10,G,G3,Paralegal,4 years,RENT,45000.0,Source Verified,Dec-2015,n,NaN,debt_consolidation,Debt consolidation,RI,17.44,0.0,Apr-2008,660.0,664.0,3.0,24.0,95.0,30.0,1.0,14276.0,40.6,42.0,w,0.0,0.0,25280.541586,25280.54,17125.00,8155.54,0.0,0.00,0.0000,Dec-2017,13792.01,NaN,Mar-2019,564.0,560.0,0.0,24.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,15199.0,4.0,3.0,0.0,0.0,67.0,923.0,39.0,4.0,13.0,1838.0,40.0,35200.0,5.0,0.0,8.0,13.0,524.0,4267.0,71.0,0.0,0.0,69.0,92.0,2.0,2.0,0.0,2.0,42.0,0.0,42.0,3.0,9.0,17.0,10.0,15.0,8.0,27.0,34.0,17.0,30.0,0.0,0.0,0.0,4.0,76.2,60.0,1.0,0.0,37575.0,15199.0,14700.0,2375.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
764,11750.0,60 months,28.49,369.33,G,G4,Seamstress,1 year,OWN,28000.0,Verified,Dec-2015,n,NaN,debt_consolidation,Debt consolidation,MS,22.16,0.0,Jan-2001,690.0,694.0,1.0,31.0,NaN,11.0,0.0,9758.0,25.1,20.0,w,0.0,0.0,4798.760000,4798.76,1006.57,2640.24,0.0,1151.95,207.3510,Nov-2016,369.33,NaN,Apr-2017,539.0,535.0,0.0,31.0,1.0,Individual,NaN,NaN,NaN,0.0,116.0,17672.0,1.0,1.0,1.0,2.0,9.0,7914.0,94.0,1.0,2.0,5944.0,37.0,38800.0,0.0,0.0,1.0,4.0,1767.0,15958.0,32.9,0.0,0.0,100.0,179.0,5.0,5.0,0.0,5.0,NaN,5.0,NaN,1.0,3.0,5.0,4.0,8.0,5.0,9.0,14.0,5.0,11.0,0.0,0.0,0.0,2.0,95.0,50.0,0.0,0.0,47235.0,17672.0,23800.0,8435.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
892,16275.0,60 months,27.49,501.74,G,G2,Customer care,1 year,RENT,37000.0,Verified,Dec-2015,n,NaN,debt_consolidation,Debt consolidation,AZ,18.72,0.0,Oct-2011,685.0,689.0,1.0,NaN,NaN,10.0,0.0,1688.0,12.3,15.0,w,0.0,0.0,941.340000,941.34,260.77,680.57,0.0,0.00,0.0000,Mar-2016,501.74,NaN,Jan-2019,614.0,610.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,1203.0,23573.0,3.0,2.0,1.0,2.0,5.0,21885.0,88.0,2.0,6.0,918.0,61.0,13700.0,3.0,2.0,5.0,8.0,2357.0,7182.0,11.3,0.0,0.0,40.0,50.0,2.0,2.0,0.0,2.0,NaN,0.0,NaN,0.0,1.0,2.0,4.0,7.0,4.0,8.0,11.0,2.0,10.0,0.0,0.0,0.0,3.0,100.0,25.0,0.0,0.0,38652.0,23573.0,8100.0,24952.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1343869,6000.0,36 months,28.18,248.77,G,G1,Cafeteria Manager,5 years,RENT,30000.0,Verified,Oct-2016,n,NaN,other,Other,FL,1.92,8.0,Mar-2001,660.0,664.0,0.0,10.0,NaN,9.0,0.0,1361.0,59.2,25.0,f,0.0,0.0,8055.960334,8055.96,6000.00,2055.96,0.0,0.00,0.0000,Mar-2018,4061.97,NaN,Mar-2019,659.0,655.0,0.0,10.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,29963.0,0.0,6.0,0.0,0.0,63.0,28602.0,106.0,0.0,2.0,604.0,102.0,2300.0,0.0,1.0,0.0,2.0,3329.0,696.0,46.5,0.0,0.0,78.0,186.0,16.0,16.0,2.0,16.0,23.0,14.0,23.0,8.0,1.0,2.0,2.0,8.0,13.0,3.0,10.0,2.0,9.0,0.0,0.0,7.0,0.0,57.1,0.0,0.0,0.0,29300.0,29963.0,1300.0,27000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1343943,12600.0,60 months,28.88,399.03,G,G2,Vice President Special Assets,2 years,RENT,122000.0,Not Verified,Oct-2016,n,NaN,major_purchase,Major purchase,NC,20.39,1.0,May-2006,670.0,674.0,1.0,6.0,20.0,7.0,3.0,4318.0,46.9,24.0,f,0.0,0.0,9140.310000,9140.31,1983.08,4632.14,0.0,2525.09,454.5162,Feb-2018,399.03,NaN,Aug-2018,514.0,510.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,84014.0,0.0,3.0,1.0,4.0,8.0,79696.0,2.0,2.0,3.0,3153.0,28.0,9200.0,19.0,1.0,8.0,7.0,12002.0,4882.0,46.9,0.0,0.0,122.0,124.0,11.0,8.0,0.0,11.0,NaN,0.0,NaN,0.0,3.0,3.0,4.0,5.0,19.0,4.0,5.0,3.0,7.0,0.0,0.0,0.0,3.0,90.5,25.0,0.0,3.0,105436.0,84014.0,9200.0,96236.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1344334,13000.0,60 months,28.88,411.70,G,G2,Core Systems Administrator,< 1 year,RENT,73000.0,Verified,Oct-2016,n,NaN,house,Home buying,IN,6.92,1.0,Jul-2006,700.0,704.0,5.0,21.0,NaN,9.0,0.0,3500.0,32.1,19.0,w,0.0,0.0,15309.784554,15309.78,13000.00,2309.78,0.0,0.00,0.0000,Jun-2017,6480.02,NaN,Apr-2018,664.0,660.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,52644.0,2.0,3.0,1.0,3.0,3.0,25384.0,95.0,1.0,2.0,3500.0,77.0,10900.0,5.0,6.0,16.0,6.0,5849.0,2000.0,63.6,0.0,0.0,122.0,82.0,3.0,3.0,2.0,3.0,NaN,0.0,25.0,0.0,1.0,1.0,2.0,4.0,10.0,5.0,7.0,1.0,9.0,0.0,0.0,0.0,3.0,88.9,0.0,0.0,0.0,62333.0,28884.0,5500.0,26633.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1344734,15875.0,60 months,28.88,502.75,G,G2,Testing analyst,10+ years,RENT,41600.0,Verified,Oct-2016,n,NaN,debt_consolidation,Debt consolidation,OH,28.02,0.0,Mar-2005,665.0,669.0,0.0,NaN,42.0,18.0,1.0,5829.0,35.1,32.0,f,0.0,0.0,16078.770000,16078.77,15875.00,203.77,0.0,0.00,0.0000,Oct-2016,16104.24,NaN,Mar-2019,689.0,685.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,22572.0,2.0,3.0,2.0,3.0,4.0,16743.0,61.0,2.0,11.0,2902.0,51.0,16600.0,1.0,2.0,1.0,14.0,1254.0,7338.0,36.7,0.0,0.0,112.0,138.0,6.0,4.0,1.0,18.0,NaN,9.0,NaN,0.0,5.0,8.0,9.0,14.0,6.0,15.0,25.0,8.0,18.0,0.0,0.0,0.0,4.0,100.0,22.2,1.0,0.0,44139.0,22572.0,11600.0,27539.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1344914,20200.0,60 months,29.96,653.05,G,G4,coater,1 year,RENT,55000.0,Verified,Oct-2016,n,NaN,debt_consolidation,Debt consolidation,CA,34.61,0.0,Nov-2005,735.0,739.0,1.0,NaN,NaN,22.0,0.0,6203.0,15.5,33.0,w,0.0,0.0,3271.500000,3271.50,301.16,971.32,0.0,1999.02,359.8236,Dec-2016,653.05,NaN,Dec-2018,634.0,630.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,51429.0,3.0,4.0,3.0,4.0,2.0,45226.0,69.0,2.0,5.0,1932.0,49.0,40200.0,1.0,2.0,6.0,9.0,2338.0,4673.0,45.0,0.0,0.0,130.0,112.0,4.0,2.0,0.0,41.0,NaN,0.0,NaN,0.0,5.0,11.0,5.0,6.0,12.0,18.0,21.0,11.0,22.0,0.0,0.0,0.0,5.0,100.0,20.0,0.0,0.0,105721.0,51429.0,8500.0,65521.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [23]:
G_total = G[['sub_grade', 'loan_status_bin']].groupby(by=['sub_grade']).count()
G_total = G_total.rename(columns={'loan_status_bin':'total loans'})
G_total

           total loans
sub_grade
G1                2997
G2                2131
G3                1614
G4                1280
G5                1110

In [24]:
#Number of G loans that are "fully paid" by sub_grade
G_paid = G[G.loan_status_bin==0][['sub_grade', 'loan_status_bin']].groupby(by=['sub_grade']).count()
G_paid = G_paid.rename(columns={'loan_status_bin':'fully_paid'})
G_paid

           fully_paid
sub_grade
G1               1434
G2               1047
G3                829
G4                655
G5                595

In [25]:
#Number of G loans that are "chargd off" by sub_grade
G_defaults = G[G.loan_status_bin!=0][['sub_grade', 'loan_status_bin']].groupby(by=['sub_grade']).count()
G_defaults = G_defaults.rename(columns={'loan_status_bin':'defaults'})
G_defaults

           defaults
sub_grade
G1             1563
G2             1084
G3              785
G4              625
G5              515

In [26]:
G_combo = pd.concat([G_total, G_paid, G_defaults], axis=1)
G_combo

           total loans  fully_paid  defaults
sub_grade
G1                2997        1434      1563
G2                2131        1047      1084
G3                1614         829       785
G4                1280         655       625
G5                1110         595       515

In [27]:
G_combo['default_ratio'] = G_combo['defaults']/G_combo['total loans']
G_combo

           total loans  fully_paid  defaults  default_ratio
sub_grade
G1                2997        1434      1563       0.521522
G2                2131        1047      1084       0.508681
G3                1614         829       785       0.486369
G4                1280         655       625       0.488281
G5                1110         595       515       0.463964

In [28]:
#Default ratio is approx 50/50 for each sub_grade of G. It's a coin toss.

In [29]:
G.head(2)

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,desc,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
305,30000.0,60 months,27.49,924.87,G,G2,Service Technian Lead,1 year,MORTGAGE,115000.0,Verified,Dec-2015,n,NaN,other,Other,CO,17.73,0.0,Oct-2001,675.0,679.0,2.0,NaN,NaN,14.0,0.0,50634.0,58.7,20.0,w,0.0,0.0,13015.23,13015.23,2934.76,7124.27,0.0,2956.2,532.116,Dec-2016,924.87,NaN,Jun-2017,534.0,530.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,300130.0,3.0,3.0,2.0,3.0,1.0,20011.0,82.0,4.0,6.0,21644.0,64.0,86200.0,3.0,1.0,7.0,9.0,23087.0,31947.0,54.5,0.0,0.0,58.0,170.0,6.0,1.0,4.0,7.0,NaN,1.0,NaN,0.0,5.0,6.0,7.0,8.0,4.0,10.0,12.0,6.0,14.0,0.0,0.0,0.0,6.0,100.0,28.6,0.0,0.0,348717.0,70645.0,70200.0,24517.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
337,19225.0,60 months,26.99,586.93,G,G1,OTR Truck Driver,< 1 year,MORTGAGE,56600.0,Verified,Dec-2015,n,NaN,debt_consolidation,NaN,OH,18.21,0.0,Apr-1990,710.0,714.0,1.0,51.0,28.0,8.0,1.0,7055.0,44.7,22.0,w,0.0,0.0,14014.25,14014.25,4846.64,9167.61,0.0,0.0,0.000,Jan-2018,586.93,NaN,Mar-2019,499.0,0.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,125.0,33946.0,5.0,3.0,3.0,3.0,3.0,26891.0,93.0,2.0,2.0,605.0,76.0,15800.0,2.0,4.0,5.0,5.0,4243.0,5847.0,12.7,0.0,0.0,122.0,308.0,2.0,2.0,0.0,2.0,NaN,0.0,51.0,0.0,2.0,4.0,3.0,5.0,10.0,5.0,12.0,4.0,8.0,0.0,0.0,0.0,5.0,90.5,33.3,0.0,1.0,44633.0,33946.0,6700.0,28833.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [30]:
top_13 = ['loan_amnt', 'term', 'int_rate', 'installment', 'sub_grade',
          'emp_length', 'annual_inc', 'verification_status', 'pymnt_plan',
          'dti', 'fico_range_low', 'loan_status_bin', 'home_ownership',
          'pub_rec']

In [31]:
G_top_13 = G[top_13].reset_index(drop=True)
G_top_13.head(5)

,loan_amnt,term,int_rate,installment,sub_grade,emp_length,annual_inc,verification_status,pymnt_plan,dti,fico_range_low,loan_status_bin,home_ownership,pub_rec
0,30000.0,60 months,27.49,924.87,G2,1 year,115000.0,Verified,n,17.73,675.0,0.0,MORTGAGE,0.0
1,19225.0,60 months,26.99,586.93,G1,< 1 year,56600.0,Verified,n,18.21,710.0,0.0,MORTGAGE,1.0
2,17125.0,60 months,27.99,533.10,G3,4 years,45000.0,Source Verified,n,17.44,660.0,1.0,RENT,1.0
3,11750.0,60 months,28.49,369.33,G4,1 year,28000.0,Verified,n,22.16,690.0,0.0,OWN,0.0
4,16275.0,60 months,27.49,501.74,G2,1 year,37000.0,Verified,n,18.72,685.0,0.0,RENT,0.0

In [32]:
G_top_13.dtypes

loan_amnt              float64
term                    object
int_rate               float64
installment            float64
sub_grade               object
emp_length              object
annual_inc             float64
verification_status     object
pymnt_plan              object
dti                    float64
fico_range_low         float64
loan_status_bin        float64
home_ownership          object
pub_rec                float64
dtype: object

In [33]:
G_top_13.isna().sum()

loan_amnt                0
term                     0
int_rate                 0
installment              0
sub_grade                0
emp_length             445
annual_inc               0
verification_status      0
pymnt_plan               0
dti                      6
fico_range_low           0
loan_status_bin          0
home_ownership           0
pub_rec                  0
dtype: int64

In [34]:
#Encoding Functions

def binary_temp(df, column, positive_value):
    temp_df = df.assign(new_be=df[column].apply(lambda x: 1 if x == positive_value else 0))
    return temp_df

def binary_encode(temp_df, column):
    new_df = temp_df.drop(column, axis=1)
    new_df = new_df.rename(columns={'new_be':column})
    return new_df
    
    #df[column + '_be'] = df[column].apply(lambda x: 1 if x == positive_value else 0)
    #df_new = pd.concat([df, df[column].apply(lambda x: 1 if x == positive_value else 0)], axis=1)
    #df_new = df_new.drop(column, axis=1)
    #return df_new

def ordinal_temp(df, column, ordering):
    temp_df = df.assign(new_oe=df[column].apply(lambda x: ordering.index(x)))
    return temp_df

def ordinal_encode(temp_df, column):
    new_df = temp_df.drop(column, axis=1)
    new_df = new_df.rename(columns={'new_oe':column})
    return new_df

def onehot_encode(df, column):
    dummies = pd.get_dummies(df[column])
    df_new = pd.concat([df, dummies], axis=1)
    df_new = df_new.drop(column, axis=1)
    return df_new

In [35]:
#Return unique values of categorical columns:
{column: list(G_top_13[column].unique()) for column in G_top_13.columns if G_top_13.dtypes[column]=='object'}

{'term': [' 60 months', ' 36 months'],
 'sub_grade': ['G2', 'G1', 'G3', 'G4', 'G5'],
 'emp_length': ['1 year',
  '< 1 year',
  '4 years',
  '3 years',
  '10+ years',
  '5 years',
  '2 years',
  '8 years',
  '9 years',
  '6 years',
  '7 years',
  nan],
 'verification_status': ['Verified', 'Source Verified', 'Not Verified'],
 'pymnt_plan': ['n'],
 'home_ownership': ['MORTGAGE', 'RENT', 'OWN', 'ANY', 'NONE']}

In [36]:
#Check Binary Encoding:

temp = binary_temp(G_top_13, 'term', ' 60 months')

#for feature, positive_value in zip(binary_features, binary_positives):
#    df2 = binary_encode(df, feature, positive_value)

In [37]:
temp[['term', 'new_be']].sample(10)

            term  new_be
4795   60 months       1
8659   36 months       0
6404   60 months       1
8188   60 months       1
2756   60 months       1
5896   60 months       1
963    60 months       1
2968   36 months       0
8242   60 months       1
5533   60 months       1

In [38]:
#If ok, complete binary encoding:
new_df = binary_encode(temp, 'term')
new_df.head(5)

,loan_amnt,int_rate,installment,sub_grade,emp_length,annual_inc,verification_status,pymnt_plan,dti,fico_range_low,loan_status_bin,home_ownership,pub_rec,term
0,30000.0,27.49,924.87,G2,1 year,115000.0,Verified,n,17.73,675.0,0.0,MORTGAGE,0.0,1
1,19225.0,26.99,586.93,G1,< 1 year,56600.0,Verified,n,18.21,710.0,0.0,MORTGAGE,1.0,1
2,17125.0,27.99,533.10,G3,4 years,45000.0,Source Verified,n,17.44,660.0,1.0,RENT,1.0,1
3,11750.0,28.49,369.33,G4,1 year,28000.0,Verified,n,22.16,690.0,0.0,OWN,0.0,1
4,16275.0,27.49,501.74,G2,1 year,37000.0,Verified,n,18.72,685.0,0.0,RENT,0.0,1

In [39]:
grade_ordering = ['G1', 'G2', 'G3', 'G4', 'G5']

In [40]:
temp_df = ordinal_temp(new_df, 'sub_grade', grade_ordering)
temp_df[['sub_grade', 'new_oe']]

     sub_grade  new_oe
0           G2       1
1           G1       0
2           G3       2
3           G4       3
4           G2       1
...        ...     ...
9127        G1       0
9128        G2       1
9129        G2       1
9130        G2       1
9131        G4       3

[9132 rows x 2 columns]

In [41]:
#If ok, complete ordinal encoding:
new_df = ordinal_encode(temp_df, 'sub_grade')
new_df.head(5)

,loan_amnt,int_rate,installment,emp_length,annual_inc,verification_status,pymnt_plan,dti,fico_range_low,loan_status_bin,home_ownership,pub_rec,term,sub_grade
0,30000.0,27.49,924.87,1 year,115000.0,Verified,n,17.73,675.0,0.0,MORTGAGE,0.0,1,1
1,19225.0,26.99,586.93,< 1 year,56600.0,Verified,n,18.21,710.0,0.0,MORTGAGE,1.0,1,0
2,17125.0,27.99,533.10,4 years,45000.0,Source Verified,n,17.44,660.0,1.0,RENT,1.0,1,2
3,11750.0,28.49,369.33,1 year,28000.0,Verified,n,22.16,690.0,0.0,OWN,0.0,1,3
4,16275.0,27.49,501.74,1 year,37000.0,Verified,n,18.72,685.0,0.0,RENT,0.0,1,1

In [42]:
new_df['emp_length'].replace(np.nan, "None", inplace=True)

In [43]:
new_df['emp_length'].value_counts()

10+ years    3048
2 years       814
3 years       738
< 1 year      736
1 year        616
5 years       570
4 years       536
6 years       450
None          445
7 years       432
8 years       401
9 years       346
Name: emp_length, dtype: int64

In [44]:
emp_ordering = [
    'None',
    '< 1 year',
    '1 year',
    '2 years',
    '3 years',
    '4 years',
    '5 years',
    '6 years',
    '7 years',
    '8 years',
    '9 years',
    '10+ years',
    ]

In [45]:
temp_df = ordinal_temp(new_df, 'emp_length', emp_ordering)
temp_df[['emp_length', 'new_oe']]

     emp_length  new_oe
0        1 year       2
1      < 1 year       1
2       4 years       5
3        1 year       2
4        1 year       2
...         ...     ...
9127    5 years       6
9128    2 years       3
9129   < 1 year       1
9130  10+ years      11
9131     1 year       2

[9132 rows x 2 columns]

In [46]:
new_df = ordinal_encode(temp_df, 'emp_length')
new_df.head(3)

,loan_amnt,int_rate,installment,annual_inc,verification_status,pymnt_plan,dti,fico_range_low,loan_status_bin,home_ownership,pub_rec,term,sub_grade,emp_length
0,30000.0,27.49,924.87,115000.0,Verified,n,17.73,675.0,0.0,MORTGAGE,0.0,1,1,2
1,19225.0,26.99,586.93,56600.0,Verified,n,18.21,710.0,0.0,MORTGAGE,1.0,1,0,1
2,17125.0,27.99,533.10,45000.0,Source Verified,n,17.44,660.0,1.0,RENT,1.0,1,2,5

In [47]:
#Dummify nominal features:
numerical_df = onehot_encode(new_df, 'verification_status')
numerical_df

,loan_amnt,int_rate,installment,annual_inc,pymnt_plan,dti,fico_range_low,loan_status_bin,home_ownership,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified
0,30000.0,27.49,924.87,115000.0,n,17.73,675.0,0.0,MORTGAGE,0.0,1,1,2,0,0,1
1,19225.0,26.99,586.93,56600.0,n,18.21,710.0,0.0,MORTGAGE,1.0,1,0,1,0,0,1
2,17125.0,27.99,533.10,45000.0,n,17.44,660.0,1.0,RENT,1.0,1,2,5,0,1,0
3,11750.0,28.49,369.33,28000.0,n,22.16,690.0,0.0,OWN,0.0,1,3,2,0,0,1
4,16275.0,27.49,501.74,37000.0,n,18.72,685.0,0.0,RENT,0.0,1,1,2,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9127,6000.0,28.18,248.77,30000.0,n,1.92,660.0,1.0,RENT,0.0,0,0,6,0,0,1
9128,12600.0,28.88,399.03,122000.0,n,20.39,670.0,0.0,RENT,3.0,1,1,3,1,0,0
9129,13000.0,28.88,411.70,73000.0,n,6.92,700.0,1.0,RENT,0.0,1,1,1,0,0,1
9130,15875.0,28.88,502.75,41600.0,n,28.02,665.0,1.0,RENT,1.0,1,1,11,0,0,1
9131,20200.0,29.96,653.05,55000.0,n,34.61,735.0,0.0,RENT,0.0,1,3,2,0,0,1

In [48]:
#For G loans, all of them don't have payment plan, so we will drop this feature. 
numerical_df.pymnt_plan.value_counts()

n    9132
Name: pymnt_plan, dtype: int64

In [49]:
numerical_df = numerical_df.drop('pymnt_plan', axis=1)
numerical_df

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,loan_status_bin,home_ownership,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified
0,30000.0,27.49,924.87,115000.0,17.73,675.0,0.0,MORTGAGE,0.0,1,1,2,0,0,1
1,19225.0,26.99,586.93,56600.0,18.21,710.0,0.0,MORTGAGE,1.0,1,0,1,0,0,1
2,17125.0,27.99,533.10,45000.0,17.44,660.0,1.0,RENT,1.0,1,2,5,0,1,0
3,11750.0,28.49,369.33,28000.0,22.16,690.0,0.0,OWN,0.0,1,3,2,0,0,1
4,16275.0,27.49,501.74,37000.0,18.72,685.0,0.0,RENT,0.0,1,1,2,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9127,6000.0,28.18,248.77,30000.0,1.92,660.0,1.0,RENT,0.0,0,0,6,0,0,1
9128,12600.0,28.88,399.03,122000.0,20.39,670.0,0.0,RENT,3.0,1,1,3,1,0,0
9129,13000.0,28.88,411.70,73000.0,6.92,700.0,1.0,RENT,0.0,1,1,1,0,0,1
9130,15875.0,28.88,502.75,41600.0,28.02,665.0,1.0,RENT,1.0,1,1,11,0,0,1
9131,20200.0,29.96,653.05,55000.0,34.61,735.0,0.0,RENT,0.0,1,3,2,0,0,1

In [50]:
#Dummify nominal features:
numerical_df2 = onehot_encode(numerical_df, 'home_ownership')
numerical_df2

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,loan_status_bin,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified,ANY,MORTGAGE,NONE,OWN,RENT
0,30000.0,27.49,924.87,115000.0,17.73,675.0,0.0,0.0,1,1,2,0,0,1,0,1,0,0,0
1,19225.0,26.99,586.93,56600.0,18.21,710.0,0.0,1.0,1,0,1,0,0,1,0,1,0,0,0
2,17125.0,27.99,533.10,45000.0,17.44,660.0,1.0,1.0,1,2,5,0,1,0,0,0,0,0,1
3,11750.0,28.49,369.33,28000.0,22.16,690.0,0.0,0.0,1,3,2,0,0,1,0,0,0,1,0
4,16275.0,27.49,501.74,37000.0,18.72,685.0,0.0,0.0,1,1,2,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9127,6000.0,28.18,248.77,30000.0,1.92,660.0,1.0,0.0,0,0,6,0,0,1,0,0,0,0,1
9128,12600.0,28.88,399.03,122000.0,20.39,670.0,0.0,3.0,1,1,3,1,0,0,0,0,0,0,1
9129,13000.0,28.88,411.70,73000.0,6.92,700.0,1.0,0.0,1,1,1,0,0,1,0,0,0,0,1
9130,15875.0,28.88,502.75,41600.0,28.02,665.0,1.0,1.0,1,1,11,0,0,1,0,0,0,0,1
9131,20200.0,29.96,653.05,55000.0,34.61,735.0,0.0,0.0,1,3,2,0,0,1,0,0,0,0,1

In [51]:
#All features are now in numerical form. 
numerical_df2.dtypes

loan_amnt          float64
int_rate           float64
installment        float64
annual_inc         float64
dti                float64
fico_range_low     float64
loan_status_bin    float64
pub_rec            float64
term                 int64
sub_grade            int64
emp_length           int64
Not Verified         uint8
Source Verified      uint8
Verified             uint8
ANY                  uint8
MORTGAGE             uint8
NONE                 uint8
OWN                  uint8
RENT                 uint8
dtype: object

In [52]:
#Check if any missing values left, especially in numerical columns which were not transformed:
numerical_df2.isna().sum()  #6 values in dti. Let's drop them.

loan_amnt          0
int_rate           0
installment        0
annual_inc         0
dti                6
fico_range_low     0
loan_status_bin    0
pub_rec            0
term               0
sub_grade          0
emp_length         0
Not Verified       0
Source Verified    0
Verified           0
ANY                0
MORTGAGE           0
NONE               0
OWN                0
RENT               0
dtype: int64

In [56]:
numerical_df2[numerical_df2.dti.isna()]

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,loan_status_bin,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified,ANY,MORTGAGE,NONE,OWN,RENT
1898,35000.0,30.79,1149.42,0.0,NaN,730.0,1.0,0.0,1,0,0,1,0,0,0,1,0,0,0
2429,30000.0,30.84,986.14,0.0,NaN,670.0,0.0,0.0,1,1,0,1,0,0,0,0,0,0,1
3503,12225.0,30.79,524.28,0.0,NaN,665.0,1.0,1.0,0,0,0,1,0,0,0,1,0,0,0
4238,17600.0,28.99,558.55,0.0,NaN,660.0,0.0,0.0,1,4,0,1,0,0,0,0,0,0,1
6293,24850.0,30.79,816.09,0.0,NaN,710.0,0.0,0.0,1,0,0,1,0,0,0,0,0,0,1
8655,10000.0,30.79,328.41,0.0,NaN,675.0,0.0,0.0,1,0,0,1,0,0,0,0,0,1,0

In [58]:
numerical_df2[numerical_df2.annual_inc==0]

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,loan_status_bin,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified,ANY,MORTGAGE,NONE,OWN,RENT
1898,35000.0,30.79,1149.42,0.0,NaN,730.0,1.0,0.0,1,0,0,1,0,0,0,1,0,0,0
2429,30000.0,30.84,986.14,0.0,NaN,670.0,0.0,0.0,1,1,0,1,0,0,0,0,0,0,1
3503,12225.0,30.79,524.28,0.0,NaN,665.0,1.0,1.0,0,0,0,1,0,0,0,1,0,0,0
4238,17600.0,28.99,558.55,0.0,NaN,660.0,0.0,0.0,1,4,0,1,0,0,0,0,0,0,1
6293,24850.0,30.79,816.09,0.0,NaN,710.0,0.0,0.0,1,0,0,1,0,0,0,0,0,0,1
8655,10000.0,30.79,328.41,0.0,NaN,675.0,0.0,0.0,1,0,0,1,0,0,0,0,0,1,0

In [66]:
numerical_df2.dti.describe()

count    9126.000000
mean       21.516503
std        16.290095
min         0.000000
25%        14.352500
50%        20.920000
75%        27.750000
max       999.000000
Name: dti, dtype: float64

In [78]:
#Drop these 6 observations for now, may revisit later....

numerical_df2 = numerical_df2.dropna().reset_index(drop=True)
numerical_df2

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,loan_status_bin,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified,ANY,MORTGAGE,NONE,OWN,RENT
0,30000.0,27.49,924.87,115000.0,17.73,675.0,0.0,0.0,1,1,2,0,0,1,0,1,0,0,0
1,19225.0,26.99,586.93,56600.0,18.21,710.0,0.0,1.0,1,0,1,0,0,1,0,1,0,0,0
2,17125.0,27.99,533.10,45000.0,17.44,660.0,1.0,1.0,1,2,5,0,1,0,0,0,0,0,1
3,11750.0,28.49,369.33,28000.0,22.16,690.0,0.0,0.0,1,3,2,0,0,1,0,0,0,1,0
4,16275.0,27.49,501.74,37000.0,18.72,685.0,0.0,0.0,1,1,2,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9121,6000.0,28.18,248.77,30000.0,1.92,660.0,1.0,0.0,0,0,6,0,0,1,0,0,0,0,1
9122,12600.0,28.88,399.03,122000.0,20.39,670.0,0.0,3.0,1,1,3,1,0,0,0,0,0,0,1
9123,13000.0,28.88,411.70,73000.0,6.92,700.0,1.0,0.0,1,1,1,0,0,1,0,0,0,0,1
9124,15875.0,28.88,502.75,41600.0,28.02,665.0,1.0,1.0,1,1,11,0,0,1,0,0,0,0,1
9125,20200.0,29.96,653.05,55000.0,34.61,735.0,0.0,0.0,1,3,2,0,0,1,0,0,0,0,1

In [79]:
X = numerical_df2.drop('loan_status_bin', axis=1)
y = numerical_df2['loan_status_bin']

In [80]:
X

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified,ANY,MORTGAGE,NONE,OWN,RENT
0,30000.0,27.49,924.87,115000.0,17.73,675.0,0.0,1,1,2,0,0,1,0,1,0,0,0
1,19225.0,26.99,586.93,56600.0,18.21,710.0,1.0,1,0,1,0,0,1,0,1,0,0,0
2,17125.0,27.99,533.10,45000.0,17.44,660.0,1.0,1,2,5,0,1,0,0,0,0,0,1
3,11750.0,28.49,369.33,28000.0,22.16,690.0,0.0,1,3,2,0,0,1,0,0,0,1,0
4,16275.0,27.49,501.74,37000.0,18.72,685.0,0.0,1,1,2,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9121,6000.0,28.18,248.77,30000.0,1.92,660.0,0.0,0,0,6,0,0,1,0,0,0,0,1
9122,12600.0,28.88,399.03,122000.0,20.39,670.0,3.0,1,1,3,1,0,0,0,0,0,0,1
9123,13000.0,28.88,411.70,73000.0,6.92,700.0,0.0,1,1,1,0,0,1,0,0,0,0,1
9124,15875.0,28.88,502.75,41600.0,28.02,665.0,1.0,1,1,11,0,0,1,0,0,0,0,1
9125,20200.0,29.96,653.05,55000.0,34.61,735.0,0.0,1,3,2,0,0,1,0,0,0,0,1

In [81]:
y

0       0.0
1       0.0
2       1.0
3       0.0
4       0.0
       ...
9121    1.0
9122    0.0
9123    1.0
9124    1.0
9125    0.0
Name: loan_status_bin, Length: 9126, dtype: float64

In [82]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_scaled = sc.fit_transform(X)

In [83]:
X = pd.DataFrame(X_scaled, columns=X.columns)
X

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified,ANY,MORTGAGE,NONE,OWN,RENT
0,1.048421,-0.091987,0.896021,0.757086,-0.232455,-0.185394,-0.403489,0.446684,-0.356910,-1.192676,-0.255685,-0.707630,0.808060,-0.02094,1.094521,-0.010468,-0.366949,-0.861164
1,-0.151844,-0.288444,-0.256434,-0.383695,-0.202987,1.630793,1.202374,0.446684,-1.079438,-1.449304,-0.255685,-0.707630,0.808060,-0.02094,1.094521,-0.010468,-0.366949,-0.861164
2,-0.385771,0.104469,-0.440006,-0.610289,-0.250258,-0.963760,1.202374,0.446684,0.365619,-0.422792,-0.255685,1.413168,-1.237531,-0.02094,-0.913641,-0.010468,-0.366949,1.161219
3,-0.984511,0.300926,-0.998500,-0.942366,0.039504,0.592972,-0.403489,0.446684,1.088147,-1.192676,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,2.725178,-0.861164
4,-0.480455,-0.091987,-0.546951,-0.766560,-0.171678,0.333516,-0.403489,0.446684,-0.356910,-1.192676,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9121,-1.625023,0.179123,-1.409638,-0.903298,-1.203036,-0.963760,-0.403489,-2.238718,-1.079438,-0.166164,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219
9122,-0.889826,0.454162,-0.897216,0.893823,-0.069156,-0.444850,4.414100,0.446684,-0.356910,-0.936048,3.911065,-0.707630,-1.237531,-0.02094,-0.913641,-0.010468,-0.366949,1.161219
9123,-0.845269,0.454162,-0.854009,-0.063339,-0.896085,1.111882,-0.403489,0.446684,-0.356910,-1.449304,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219
9124,-0.525012,0.454162,-0.543507,-0.676704,0.399252,-0.704305,1.202374,0.446684,-0.356910,1.116976,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219
9125,-0.043235,0.878508,-0.030949,-0.414950,0.803814,2.928070,-0.403489,0.446684,1.088147,-1.192676,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219

In [84]:
scaled = pd.concat([X,y], axis=1)
scaled

,loan_amnt,int_rate,installment,annual_inc,dti,fico_range_low,pub_rec,term,sub_grade,emp_length,Not Verified,Source Verified,Verified,ANY,MORTGAGE,NONE,OWN,RENT,loan_status_bin
0,1.048421,-0.091987,0.896021,0.757086,-0.232455,-0.185394,-0.403489,0.446684,-0.356910,-1.192676,-0.255685,-0.707630,0.808060,-0.02094,1.094521,-0.010468,-0.366949,-0.861164,0.0
1,-0.151844,-0.288444,-0.256434,-0.383695,-0.202987,1.630793,1.202374,0.446684,-1.079438,-1.449304,-0.255685,-0.707630,0.808060,-0.02094,1.094521,-0.010468,-0.366949,-0.861164,0.0
2,-0.385771,0.104469,-0.440006,-0.610289,-0.250258,-0.963760,1.202374,0.446684,0.365619,-0.422792,-0.255685,1.413168,-1.237531,-0.02094,-0.913641,-0.010468,-0.366949,1.161219,1.0
3,-0.984511,0.300926,-0.998500,-0.942366,0.039504,0.592972,-0.403489,0.446684,1.088147,-1.192676,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,2.725178,-0.861164,0.0
4,-0.480455,-0.091987,-0.546951,-0.766560,-0.171678,0.333516,-0.403489,0.446684,-0.356910,-1.192676,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9121,-1.625023,0.179123,-1.409638,-0.903298,-1.203036,-0.963760,-0.403489,-2.238718,-1.079438,-0.166164,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219,1.0
9122,-0.889826,0.454162,-0.897216,0.893823,-0.069156,-0.444850,4.414100,0.446684,-0.356910,-0.936048,3.911065,-0.707630,-1.237531,-0.02094,-0.913641,-0.010468,-0.366949,1.161219,0.0
9123,-0.845269,0.454162,-0.854009,-0.063339,-0.896085,1.111882,-0.403489,0.446684,-0.356910,-1.449304,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219,1.0
9124,-0.525012,0.454162,-0.543507,-0.676704,0.399252,-0.704305,1.202374,0.446684,-0.356910,1.116976,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219,1.0
9125,-0.043235,0.878508,-0.030949,-0.414950,0.803814,2.928070,-0.403489,0.446684,1.088147,-1.192676,-0.255685,-0.707630,0.808060,-0.02094,-0.913641,-0.010468,-0.366949,1.161219,0.0

In [85]:
scaled.to_csv('G_12_feat_scaled.csv', index=False)