In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Ten.csv')
data

,funded_amnt,int_rate,installment,annual_inc,dti,fico_range_low,loan_status_bin,term,grade,emp_length,Not Verified,Source Verified,Verified
0,3600.0,13.99,123.03,55000.0,5.91,675.0,0.0,0,2,10,1,0,0
1,24700.0,11.99,820.28,65000.0,16.06,715.0,0.0,0,2,10,1,0,0
2,20000.0,10.78,432.66,63000.0,10.78,695.0,0.0,1,1,10,1,0,0
3,10400.0,22.45,289.91,104433.0,25.37,695.0,0.0,1,5,3,0,1,0
4,11950.0,13.44,405.18,34000.0,10.20,690.0,0.0,0,2,4,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266777,18000.0,9.49,377.95,130000.0,20.59,735.0,0.0,1,1,5,1,0,0
1266778,29400.0,13.99,683.94,180792.0,22.03,705.0,0.0,1,2,9,1,0,0
1266779,32000.0,14.49,752.74,157000.0,10.34,735.0,1.0,1,2,3,0,1,0
1266780,16000.0,12.79,362.34,150000.0,12.25,665.0,0.0,1,2,10,1,0,0
1266781,24000.0,14.49,564.56,110000.0,18.30,660.0,1.0,1,2,6,1,0,0

In [9]:
X = data.drop('loan_status_bin', axis=1)
y = data['loan_status_bin']

In [10]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_scaled = sc.fit_transform(X)

In [11]:
X_scaled

array([[-1.25732782,  0.15856892, -1.21892336, ...,  1.49967509,
        -0.81569275, -0.64327554],
       [ 1.15613598, -0.26076071,  1.43780248, ...,  1.49967509,
        -0.81569275, -0.64327554],
       [ 0.61853978, -0.51445514, -0.03914276, ...,  1.49967509,
        -0.81569275, -0.64327554],
       ...,
       [ 1.99112583,  0.26340132,  1.18045538, ..., -0.6668111 ,
         1.22595181, -0.64327554],
       [ 0.1610111 , -0.09302886, -0.30708247, ...,  1.49967509,
        -0.81569275, -0.64327554],
       [ 1.07606846,  0.26340132,  0.4634347 , ...,  1.49967509,
        -0.81569275, -0.64327554]])

In [12]:
X = pd.DataFrame(X_scaled, columns=X.columns)
X

,funded_amnt,int_rate,installment,annual_inc,dti,fico_range_low,term,grade,emp_length,Not Verified,Source Verified,Verified
0,-1.257328,0.158569,-1.218923,-0.322166,-1.276775,-0.667208,-0.571945,0.197404,1.092907,1.499675,-0.815693,-0.643276
1,1.156136,-0.260761,1.437802,-0.181486,-0.216161,0.596113,-0.571945,0.197404,1.092907,1.499675,-0.815693,-0.643276
2,0.618540,-0.514455,-0.039143,-0.209622,-0.767889,-0.035548,1.748420,-0.573732,1.092907,1.499675,-0.815693,-0.643276
3,-0.479529,1.932333,-0.583062,0.373261,0.756678,-0.035548,1.748420,2.510810,-0.803529,-0.666811,1.225952,-0.643276
4,-0.302237,0.043253,-0.143850,-0.617596,-0.828496,-0.193463,-0.571945,0.197404,-0.532609,-0.666811,1.225952,-0.643276
...,...,...,...,...,...,...,...,...,...,...,...,...
1266777,0.389775,-0.784923,-0.247604,0.732940,0.257197,1.227773,1.748420,-0.573732,-0.261690,1.499675,-0.815693,-0.643276
1266778,1.693732,0.158569,0.918307,1.447486,0.407668,0.280282,1.748420,0.197404,0.821988,1.499675,-0.815693,-0.643276
1266779,1.991126,0.263401,1.180455,1.112778,-0.813867,1.227773,1.748420,0.197404,-0.803529,-0.666811,1.225952,-0.643276
1266780,0.161011,-0.093029,-0.307082,1.014302,-0.614283,-0.983039,1.748420,0.197404,1.092907,1.499675,-0.815693,-0.643276
1266781,1.076068,0.263401,0.463435,0.451578,0.017906,-1.140954,1.748420,0.197404,0.009230,1.499675,-0.815693,-0.643276

In [13]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [14]:
classification_models = []
classification_models.append(('Logistic Regression', LogisticRegression(solver="liblinear")))
classification_models.append(('K Nearest Neighbor', KNeighborsClassifier(n_neighbors=5, metric="minkowski",p=2)))
classification_models.append(('Kernel SVM', SVC(kernel = 'rbf',gamma='scale')))
classification_models.append(('Naive Bayes', GaussianNB()))
classification_models.append(('Decision Tree', DecisionTreeClassifier(criterion = "entropy")))
classification_models.append(('Random Forest', RandomForestClassifier(n_estimators=100, criterion="entropy")))

In [ ]:
for name, model in classification_models:
  kfold = KFold(n_splits=5, random_state=7, shuffle=True)
  result = cross_val_score(model, X, y, cv=kfold, scoring='accuracy')
  print("%s: Mean Accuracy = %.2f%% - SD Accuracy = %.2f%%" % (name, result.mean()*100, result.std()*100))

Logistic Regression: Mean Accuracy = 80.49% - SD Accuracy = 0.04%
K Nearest Neighbor: Mean Accuracy = 77.77% - SD Accuracy = 0.05%