In [1]:
import pandas as pd
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_row", 160)
pd.set_option('max_colwidth', 200)

In [2]:
a = pd.read_csv('../2. Data/accepted.csv')
a.head(3)

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68407277,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68355089,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.0,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68341763,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.0,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
a.shape

(2260701, 151)

In [4]:
#Data Dictionary to review features: 
pd.read_excel('../2. Data/LCDataDictionary.xlsx')

,LoanStatNew,Description
0,acc_now_delinq,The number of accounts on which the borrower is now delinquent.
1,acc_open_past_24mths,Number of trades opened in past 24 months.
2,addr_state,The state provided by the borrower in the loan application
3,all_util,Balance to credit limit on all trades
4,annual_inc,The self-reported annual income provided by the borrower during registration.
5,annual_inc_joint,The combined self-reported annual income provided by the co-borrowers during registration
6,application_type,Indicates whether the loan is an individual application or a joint application with two co-borrowers
7,avg_cur_bal,Average current balance of all accounts
8,bc_open_to_buy,Total open to buy on revolving bankcards.
9,bc_util,Ratio of total current balance to high credit/credit limit for all bankcard accounts.
10,chargeoff_within_12_mths,Number of charge-offs within 12 months
11,collection_recovery_fee,post charge off collection fee
12,collections_12_mths_ex_med,Number of collections in 12 months excluding medical collections
13,delinq_2yrs,The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years
14,delinq_amnt,The past-due amount owed for the accounts on which the borrower is now delinquent.
15,desc,Loan description provided by the borrower
16,dti,"A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly inc..."
17,dti_joint,"A ratio calculated using the co-borrowers' total monthly payments on the total debt obligations, excluding mortgages and the requested LC loan, divided by the co-borrowers' combined self-reported ..."
18,earliest_cr_line,The month the borrower's earliest reported credit line was opened
19,emp_length,Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.
20,emp_title,The job title supplied by the Borrower when applying for the loan.*
21,fico_range_high,The upper boundary range the borrower’s FICO at loan origination belongs to.
22,fico_range_low,The lower boundary range the borrower’s FICO at loan origination belongs to.
23,funded_amnt,The total amount committed to that loan at that point in time.
24,funded_amnt_inv,The total amount committed by investors for that loan at that point in time.
25,grade,LC assigned loan grade
26,home_ownership,"The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER"
27,id,A unique LC assigned ID for the loan listing.
28,il_util,Ratio of total current balance to high credit/credit limit on all install acct
29,initial_list_status,"The initial listing status of the loan. Possible values are – W, F"
30,inq_fi,Number of personal finance inquiries
31,inq_last_12m,Number of credit inquiries in past 12 months
32,inq_last_6mths,The number of inquiries in past 6 months (excluding auto and mortgage inquiries)
33,installment,The monthly payment owed by the borrower if the loan originates.
34,int_rate,Interest Rate on the loan
35,issue_d,The month which the loan was funded
36,last_credit_pull_d,The most recent month LC pulled credit for this loan
37,last_fico_range_high,The upper boundary range the borrower’s last FICO pulled belongs to.
38,last_fico_range_low,The lower boundary range the borrower’s last FICO pulled belongs to.
39,last_pymnt_amnt,Last total payment amount received
40,last_pymnt_d,Last month payment was received
41,loan_amnt,"The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value."
42,loan_status,Current status of the loan
43,max_bal_bc,Maximum current balance owed on all revolving accounts
44,member_id,A unique LC assigned Id for the borrower member.
45,mo_sin_old_il_acct,Months since oldest bank installment account opened
46,mo_sin_old_rev_tl_op,Months since oldest revolving account opened
47,mo_sin_rcnt_rev_tl_op,Months since most recent revolving account opened
48,mo_sin_rcnt_tl,Months since most recent account opened
49,mort_acc,Number of mortgage accounts.
50,mths_since_last_delinq,The number of months since the borrower's last delinquency.
51,mths_since_last_major_derog,Months since most recent 90-day or worse rating
52,mths_since_last_record,The number of months since the last public record.
53,mths_since_rcnt_il,Months since most recent installment accounts opened
54,mths_since_recent_bc,Months since most recent bankcard account opened.
55,mths_since_recent_bc_dlq,Months since most recent bankcard delinquency
56,mths_since_recent_inq,Months since most recent inquiry.
57,mths_since_recent_revol_delinq,Months since most recent revolving delinquency.
58,next_pymnt_d,Next scheduled payment date
59,num_accts_ever_120_pd,Number of accounts ever 120 or more days past due
60,num_actv_bc_tl,Number of currently active bankcard accounts
61,num_actv_rev_tl,Number of currently active revolving trades
62,num_bc_sats,Number of satisfactory bankcard accounts
63,num_bc_tl,Number of bankcard accounts
64,num_il_tl,Number of installment accounts
65,num_op_rev_tl,Number of open revolving accounts
66,num_rev_accts,Number of revolving accounts
67,num_rev_tl_bal_gt_0,Number of revolving trades with balance >0
68,num_sats,Number of satisfactory accounts
69,num_tl_120dpd_2m,Number of accounts currently 120 days past due (updated in past 2 months)
70,num_tl_30dpd,Number of accounts currently 30 days past due (updated in past 2 months)
71,num_tl_90g_dpd_24m,Number of accounts 90 or more days past due in last 24 months
72,num_tl_op_past_12m,Number of accounts opened in past 12 months
73,open_acc,The number of open credit lines in the borrower's credit file.
74,open_acc_6m,Number of open trades in last 6 months
75,open_il_12m,Number of installment accounts opened in past 12 months
76,open_il_24m,Number of installment accounts opened in past 24 months
77,open_act_il,Number of currently active installment trades
78,open_rv_12m,Number of revolving trades opened in past 12 months
79,open_rv_24m,Number of revolving trades opened in past 24 months
80,out_prncp,Remaining outstanding principal for total amount funded
81,out_prncp_inv,Remaining outstanding principal for portion of total amount funded by investors
82,pct_tl_nvr_dlq,Percent of trades never delinquent
83,percent_bc_gt_75,Percentage of all bankcard accounts > 75% of limit.
84,policy_code,publicly available policy_code=1\nnew products not publicly available policy_code=2
85,pub_rec,Number of derogatory public records
86,pub_rec_bankruptcies,Number of public record bankruptcies
87,purpose,A category provided by the borrower for the loan request.
88,pymnt_plan,Indicates if a payment plan has been put in place for the loan
89,recoveries,post charge off gross recovery
90,revol_bal,Total credit revolving balance
91,revol_util,"Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit."
92,sub_grade,LC assigned loan subgrade
93,tax_liens,Number of tax liens
94,term,The number of payments on the loan. Values are in months and can be either 36 or 60.
95,title,The loan title provided by the borrower
96,tot_coll_amt,Total collection amounts ever owed
97,tot_cur_bal,Total current balance of all accounts
98,tot_hi_cred_lim,Total high credit/credit limit
99,total_acc,The total number of credit lines currently in the borrower's credit file
100,total_bal_ex_mort,Total credit balance excluding mortgage
101,total_bal_il,Total current balance of all installment accounts
102,total_bc_limit,Total bankcard high credit/credit limit
103,total_cu_tl,Number of finance trades
104,total_il_high_credit_limit,Total installment high credit/credit limit
105,total_pymnt,Payments received to date for total amount funded
106,total_pymnt_inv,Payments received to date for portion of total amount funded by investors
107,total_rec_int,Interest received to date
108,total_rec_late_fee,Late fees received to date
109,total_rec_prncp,Principal received to date
110,total_rev_hi_lim,Total revolving high credit/credit limit
111,url,URL for the LC page with listing data.
112,verification_status,"Indicates if income was verified by LC, not verified, or if the income source was verified"
113,verified_status_joint,"Indicates if the co-borrowers' joint income was verified by LC, not verified, or if the income source was verified"
114,zip_code,The first 3 numbers of the zip code provided by the borrower in the loan application.
115,revol_bal_joint,"Sum of revolving credit balance of the co-borrowers, net of duplicate balances"
116,sec_app_fico_range_low,FICO range (high) for the secondary applicant
117,sec_app_fico_range_high,FICO range (low) for the secondary applicant
118,sec_app_earliest_cr_line,Earliest credit line at time of application for the secondary applicant
119,sec_app_inq_last_6mths,Credit inquiries in the last 6 months at time of application for the secondary applicant
120,sec_app_mort_acc,Number of mortgage accounts at time of application for the secondary applicant
121,sec_app_open_acc,Number of open trades at time of application for the secondary applicant
122,sec_app_revol_util,Ratio of total current balance to high credit/credit limit for all revolving accounts
123,sec_app_open_act_il,Number of currently active installment trades at time of application for the secondary applicant
124,sec_app_num_rev_accts,Number of revolving accounts at time of application for the secondary applicant
125,sec_app_chargeoff_within_12_mths,Number of charge-offs within last 12 months at time of application for the secondary applicant
126,sec_app_collections_12_mths_ex_med,Number of collections within last 12 months excluding medical collections at time of application for the secondary applicant
127,sec_app_mths_since_last_major_derog,Months since most recent 90-day or worse rating at time of application for the secondary applicant
128,hardship_flag,Flags whether or not the borrower is on a hardship plan
129,hardship_type,Describes the hardship plan offering
130,hardship_reason,Describes the reason the hardship plan was offered
131,hardship_status,"Describes if the hardship plan is active, pending, canceled, completed, or broken"
132,deferral_term,Amount of months that the borrower is expected to pay less than the contractual monthly payment amount due to a hardship plan
133,hardship_amount,The interest payment that the borrower has committed to make each month while they are on a hardship plan
134,hardship_start_date,The start date of the hardship plan period
135,hardship_end_date,The end date of the hardship plan period
136,payment_plan_start_date,"The day the first hardship plan payment is due. For example, if a borrower has a hardship plan period of 3 months, the start date is the start of the three-month period in which the borrower is al..."
137,hardship_length,The number of months the borrower will make smaller payments than normally obligated due to a hardship plan
138,hardship_dpd,Account days past due as of the hardship plan start date
139,hardship_loan_status,Loan Status as of the hardship plan start date
140,orig_projected_additional_accrued_interest,The original projected additional interest amount that will accrue for the given hardship payment plan as of the Hardship Start Date. This field will be null if the borrower has broken their hards...
141,hardship_payoff_balance_amount,The payoff balance amount as of the hardship plan start date
142,hardship_last_payment_amount,The last payment amount as of the hardship plan start date
143,disbursement_method,"The method by which the borrower receives their loan. Possible values are: CASH, DIRECT_PAY"
144,debt_settlement_flag,"Flags whether or not the borrower, who has charged-off, is working with a debt-settlement company."
145,debt_settlement_flag_date,The most recent date that the Debt_Settlement_Flag has been set
146,settlement_status,"The status of the borrower’s settlement plan. Possible values are: COMPLETE, ACTIVE, BROKEN, CANCELLED, DENIED, DRAFT"
147,settlement_date,The date that the borrower agrees to the settlement plan
148,settlement_amount,The loan amount that the borrower has agreed to settle for
149,settlement_percentage,The settlement amount as a percentage of the payoff balance amount on the loan
150,settlement_term,The number of months that the borrower will be on the settlement plan
151,NaN,NaN
152,NaN,* Employer Title replaces Employer Name for all loans listed after 9/23/2013

In [5]:
#1. Remove all obserations with No Funded Amount First, How many:
print(len(a[a.funded_amnt.isnull()]))

33

In [6]:
drop = a[a.funded_amnt.isnull()].index
a.drop(drop, axis=0, inplace=True)
a.shape

(2260668, 151)

In [7]:
#No more NaN funded amounts: 
a[a.funded_amnt.isna()].shape

(0, 151)

In [8]:
#2. How many value types for "loan_status"?
print(a.loan_status.value_counts(dropna=False).sum()) #Total matches

a.loan_status.value_counts(dropna=False)

2260668

Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: loan_status, dtype: int64

In [9]:
#Create new column and map Charged Off = 1, Fully Paid = 0
a['loan_status_bin'] = a['loan_status'].map({'Charged Off':1, 'Fully Paid':0})

In [13]:
#Quick Check:
a[['loan_status', 'loan_status_bin']].sample(10)

         loan_status  loan_status_bin
45334     Fully Paid              0.0
139001       Current              NaN
2219409      Current              NaN
1798185   Fully Paid              0.0
795638       Current              NaN
1188412   Fully Paid              0.0
1705666  Charged Off              1.0
371843   Charged Off              1.0
2176140      Current              NaN
1717172   Fully Paid              0.0

In [14]:
#It is not clear what "Does not meet the credit policy....." means.
#a[a.loan_status == 'Does not meet the credit policy. Status:Fully Paid']

In [15]:
#3. Few (489) loans with FICO less than 660 (as per original EDA):
a[a.fico_range_low < 660]

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
1651519,151607,NaN,1500.0,1500.0,875.000000,36 months,14.70,51.78,E,E5,Manpower,1 year,RENT,25000.0,Not Verified,Nov-2007,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=151607,I am actively looking for a loan to cover my immediate bills which need to be paid as soon as possbile. Mostly it is for rent and utilities to get me back on my feet and caught up. My grandfather ...,other,PLEASE HELP WHEN IT'S NEEDED THE MOST!!!,215xx,MD,3.84,1.0,Aug-2003,630.0,634.0,1.0,5.0,0.0,4.0,0.0,1238.0,61.9,6.0,f,0.0,0.0,1664.724606,971.09,1500.0,164.72,0.00,0.0,0.0,Sep-2008,1199.40,NaN,Aug-2008,689.0,685.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1651639,106360,NaN,2700.0,2700.0,550.000000,36 months,15.96,94.88,F,F4,Turner Construction,1 year,RENT,52200.0,Not Verified,Jul-2007,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=106360,looking to consolidate debt,debt_consolidation,Consolidation,021xx,MA,12.57,0.0,Aug-2003,625.0,629.0,1.0,0.0,0.0,12.0,0.0,3075.0,92.3,13.0,f,0.0,0.0,3415.389823,695.73,2700.0,715.39,0.00,0.0,0.0,Jul-2010,96.40,NaN,Jul-2010,679.0,675.0,NaN,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1653300,357869,NaN,4000.0,4000.0,2968.505235,36 months,15.88,140.40,E,E4,Alliedbarton Security,3 years,RENT,31000.0,Verified,Oct-2008,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=357869,I want to pay off some debt so I can raise my credit score so I can buy a house for my family. I ahve twin two year old boys and i want to buy a house sothey can have some stability. Right now w...,debt_consolidation,Debt Consolidation to improve credit,891xx,NV,21.45,0.0,Aug-2001,650.0,654.0,2.0,NaN,NaN,14.0,0.0,11157.0,54.7,17.0,f,0.0,0.0,5054.040434,3689.70,4000.0,1054.04,0.00,0.0,0.0,Nov-2011,152.31,Nov-2011,Aug-2018,534.0,530.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1653304,357084,NaN,1750.0,1750.0,133.230000,36 months,14.12,59.92,D,D5,Celanese,1 year,MORTGAGE,105000.0,Not Verified,Oct-2008,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=357084,"I just received a bill from the state of KY for taxes that I owe. I need this loan to pay that bill. Apparently there were some issues in the move. I just received the check today, so this expens...",debt_consolidation,Tax Payment Loan,410xx,KY,17.70,1.0,Oct-1997,655.0,659.0,1.0,18.0,NaN,22.0,0.0,30734.0,55.7,44.0,f,0.0,0.0,2112.587403,134.80,1750.0,362.59,0.00,0.0,0.0,Dec-2010,0.88,Jan-2011,Dec-2010,664.0,660.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1653309,356514,NaN,7500.0,6550.0,1465.802113,36 months,15.07,227.29,E,E3,Global Software Solutions,4 years,RENT,90000.0,Verified,Oct-2008,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=356514,"Hi, I'm looking to pay off higher rate credit cards. So I'm looking for lower interest rate loans that I can use to pay off the credit cards with. Thank You, Chaitanya",debt_consolidation,Pay off higher interest rate credit card,631xx,MO,18.20,0.0,Nov-2000,650.0,654.0,1.0,NaN,NaN,12.0,0.0,55753.0,79.8,15.0,f,0.0,0.0,8182.105910,1571.91,6550.0,1632.11,0.00,0.0,0.0,Oct-2011,227.25,Nov-2011,Oct-2011,714.0,710.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1654382,97606,NaN,10500.0,4000.0,1150.000000,36 months,16.91,142.43,G,G2,"VUTEC, CORP",4 years,RENT,68000.0,Not Verified,Jul-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=97606,i need refi and consolidate my debts,credit_card,refi,333xx,FL,19.62,1.0,Dec-2001,655.0,659.0,3.0,6.0,0.0,7.0,0.0,1943.0,25.6,11.0,f,0.0,0.0,5127.540196,1474.20,4000.0,1127.54,0.00,0.0,0.0,Jul-2010,143.43,Aug-2010,Jul-2010,499.0,0.0,NaN,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654386,93055,NaN,2000.0,2000.0,1025.000000,36 months,12.80,67.20,D,D4,Signs by Tomorrow,< 1 year,OWN,10000.0,Not Verified,Jul-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=93055,"Reorganizing my finances, consolidating credit card debt in order to lower my total expenses and eventually get rid of a couple of my credit cards",credit_card,Financial reorganization,280xx,NC,3.48,1.0,Apr-2004,645.0,649.0,0.0,4.0,0.0,2.0,0.0,571.0,61.9,4.0,f,0.0,0.0,2419.121043,1239.80,2000.0,419.12,0.00,0.0,0.0,Jul-2010,68.31,Jul-2010,Mar-2019,729.0,725.0,NaN,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654387,91175,NaN,6000.0,6000.0,1200.000000,36 months,13.12,202.51,D,D5,SUNY- ESF,2 years,RENT,12000.0,Not Verified,Jul-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=91175,NaN,credit_card,Credit Card,132xx,NY,4.40,0.0,Dec-2004,655.0,659.0,9.0,0.0,0.0,15.0,0.0,5251.0,49.3,16.0,f,0.0,0.0,7290.237811,1458.05,6000.0,1290.24,0.00,0.0,0.0,Jul-2010,204.65,Jul-2010,Sep-2012,664.0,660.0,NaN,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654390,90106,NaN,10000.0,10000.0,350.000000,36 months,14.70,345.18,E,E5,GA-PCOM,1 year,RENT,50000.0,Not Verified,Jul-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=90106,NaN,educational,paying for medical school help,300xx,GA,7.22,2.0,Sep-1999,650.0,654.0,0.0,1.0,0.0,14.0,0.0,10025.0,85.0,20.0,f,0.0,0.0,12622.317947,441.78,10000.0,2570.54,51.78,0.0,0.0,Aug-2010,1605.65,Sep-2010,Aug-2010,499.0,0.0,NaN,NaN,1.0,Individual,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1654397,85675,NaN,1000.0,1000.0,625.000000,36 months,14.07,34.21,E,E3,Macy's,10+ years,RENT,25000.0,Not Verified,Jun-2007,Does not meet the credit policy. Status:Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=85675,I have been working hard over the last few years to pay down my credit card debt. Just need a little more help getting rid of a few high interest cards.,other,Paying down high interest credit cards,080xx,NJ,16.27,NaN,NaN,640.0,644.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,f,0.0,0.0,1231.569372,769.73,1000.0,231.57,0.00,0.0,0.0,Jun-2010,35.27,Jul-2010,Mar-2018,629.0,625.0,NaN,NaN,1.0,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#4. Is loan_amount always equal to funded_amount??

In [17]:
# No. 2065 cases where applied loan amount is not equal to funded amount. 
len(a[a.loan_amnt != a.funded_amnt])

2065

In [18]:
#4b. Is funded_amount always equal to funded_amnt_inv?

In [19]:
#No. 151,111 cases where funded amount by investor not equal to funded amount.
len(a[a.funded_amnt != a.funded_amnt_inv])

151111

In [20]:
inv_funded = a[a.funded_amnt != a.funded_amnt_inv]
inv_funded

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_bin
1486,68576308,NaN,30000.0,30000.0,29950.0,60 months,23.13,847.96,F,F2,Mechancial Component Engineer II,8 years,RENT,87000.0,Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68576308,NaN,debt_consolidation,Debt consolidation,600xx,IL,15.92,0.0,Jul-1988,660.0,664.0,3.0,NaN,40.0,12.0,1.0,16146.0,66.0,46.0,w,0.00,0.00,40462.341533,40394.90,30000.00,10462.34,0.0,0.0,0.000,Sep-2017,24447.48,NaN,Mar-2019,684.0,680.0,0.0,37.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,41119.0,3.0,3.0,3.0,3.0,1.0,24973.0,90.0,3.0,7.0,9314.0,66.0,24600.0,1.0,1.0,4.0,10.0,3738.0,8400.0,86.0,0.0,0.0,129.0,329.0,6.0,1.0,4.0,6.0,NaN,1.0,NaN,0.0,2.0,8.0,9.0,13.0,7.0,8.0,35.0,4.0,11.0,NaN,0.0,0.0,6.0,83.0,100.0,1.0,0.0,52322.0,41119.0,16800.0,27722.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1800,68425475,NaN,15000.0,15000.0,14925.0,36 months,11.99,498.15,C,C1,Document drawer,< 1 year,RENT,40000.0,Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68425475,NaN,debt_consolidation,Debt consolidation,926xx,CA,29.77,0.0,Nov-2002,680.0,684.0,1.0,30.0,NaN,8.0,0.0,15956.0,68.5,20.0,f,0.00,0.00,17833.507947,17744.34,15000.00,2833.51,0.0,0.0,0.000,Jan-2019,0.03,NaN,Mar-2019,684.0,680.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,24039.0,2.0,1.0,1.0,1.0,3.0,8083.0,92.0,1.0,1.0,6216.0,75.0,23300.0,1.0,0.0,2.0,2.0,3005.0,5622.0,73.9,0.0,0.0,78.0,157.0,6.0,3.0,0.0,49.0,36.0,3.0,36.0,2.0,5.0,6.0,6.0,13.0,2.0,7.0,17.0,6.0,8.0,0.0,0.0,0.0,2.0,90.0,50.0,0.0,0.0,32118.0,24039.0,21500.0,8818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1827,66550774,NaN,8400.0,8400.0,8375.0,36 months,11.99,278.97,C,C1,Inside Sales/Quotations,3 years,MORTGAGE,62500.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=66550774,NaN,other,Other,431xx,OH,37.08,0.0,Nov-1989,670.0,674.0,1.0,38.0,9.0,14.0,4.0,15257.0,84.3,31.0,w,0.00,0.00,10035.255898,10005.39,8400.00,1635.26,0.0,0.0,0.000,Jan-2019,280.65,NaN,Mar-2019,689.0,685.0,0.0,62.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,274891.0,2.0,5.0,0.0,4.0,13.0,34892.0,65.0,1.0,3.0,3864.0,70.0,18100.0,3.0,0.0,3.0,8.0,22908.0,1999.0,81.5,0.0,0.0,134.0,313.0,3.0,3.0,5.0,42.0,62.0,2.0,62.0,1.0,4.0,6.0,4.0,8.0,11.0,8.0,14.0,6.0,14.0,0.0,0.0,0.0,2.0,91.7,75.0,2.0,2.0,297378.0,50149.0,10800.0,53870.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1946,67287822,NaN,15000.0,15000.0,14950.0,36 months,17.27,536.81,D,D3,Teacher,3 years,RENT,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=67287822,NaN,debt_consolidation,Debt consolidation,028xx,RI,25.81,0.0,Jul-2008,670.0,674.0,0.0,NaN,NaN,21.0,0.0,16598.0,83.8,29.0,w,0.00,0.00,19404.916226,19340.23,15000.00,4404.92,0.0,0.0,0.000,Feb-2019,7.81,NaN,Jul-2018,649.0,645.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,163210.0,3.0,12.0,3.0,6.0,4.0,146612.0,109.0,0.0,4.0,4135.0,106.0,19800.0,3.0,1.0,5.0,10.0,7772.0,205.0,98.1,0.0,0.0,89.0,79.0,15.0,4.0,0.0,23.0,NaN,4.0,NaN,0.0,4.0,8.0,4.0,4.0,20.0,9.0,9.0,8.0,21.0,0.0,0.0,0.0,3.0,100.0,100.0,0.0,0.0,154538.0,163210.0,11000.0,134738.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2582,68414926,NaN,27000.0,27000.0,26975.0,36 months,18.99,989.58,E,E1,Sr Planner,2 years,MORTGAGE,60000.0,Verified,Dec-2015,Charged Off,n,https://lendingclub.com/browse/loanDetail.action?loan_id=68414926,NaN,debt_consolidation,Debt consolidation,917xx,CA,21.40,0.0,May-1988,675.0,679.0,2.0,NaN,89.0,8.0,1.0,18131.0,78.0,14.0,w,0.00,0.00,27710.920000,27685.26,18759.61,7790.21,0.0,1161.1,208.998,Mar-2018,989.58,NaN,Oct-2018,529.0,525.0,0.0,59.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,42346.0,2.0,1.0,1.0,1.0,6.0,24215.0,93.0,2.0,5.0,6948.0,78.0,23100.0,0.0,0.0,3.0,6.0,5293.0,3400.0,99.0,0.0,0.0,6.0,327.0,3.0,3.0,0.0,3.0,NaN,4.0,NaN,0.0,3.0,7.0,3.0,3.0,1.0,7.0,12.0,6.0,8.0,NaN,0.0,0.0,3.0,100.0,100.0,1.0,0.0,49081.0,42346.0,10200.0,25981.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260535,90400857,NaN,24000.0,24000.0,23750.0,36 months,13.99,820.15,C,C3,Air Traffic Controller,10+ years,MORTGAGE,136799.0,Verified,Oct-2016,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=90400857,NaN,debt_consolidation,Debt consolidation,805xx,CO,23.25,0.0,May-1999,660.0,664.0,0.0,NaN,NaN,20.0,0.0,57198.0,60.4,48.0,f,4726.05,4676.82,24473.930000,24218.99,19273.95,5199.98,0.0,0.0,0.000,Mar-2019,820.15,Apr-2019,Mar-2019,759.0,755.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,555173.0,6.0,3.0,4.0,5.0,1.0,54589.0,93.0,4.0,5.0,13211.0,73.0,94700.0,1.0,0.0,6.0,12.0,27759.0,28807.0,60.3,0.0,0.0,124.0,208.0,1.0,1.0,4.0,1.0,NaN,5.0,NaN,0.0,6.0,10.0,11.0,18.0,15.0,16.0,29.0,10.0,20.0,0.0,0.0,0.0,10.0,100.0,45.5,0.0,0.0,601689.0,111787.0,72500.0,58807.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260623,90053125,NaN,27950.0,27950.0,27925.0,60 months,13.99,650.21,C,C3,sales manager,10+ years,RENT,71000.0,Verified,Oct-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=90053125,NaN,debt_consolidation,Debt consolidation,633xx,MO,15.70,0.0,Jun-2004,690.0,694.0,0.0,NaN,NaN,7.0,0.0,30396.0,71.0,27.0,f,0.00,0.00,33933.710078,33903.36,27950.00,5983.71,0.0,0.0,0.000,Jun-2018,21494.46,NaN,Jul-2018,739.0,735.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,812.0,357719.0,0.0,1.0,0.0,0.0,29.0,10327.0,66.0,0.0,0.0,13411.0,70.0,42800.0,0.0,3.0,0.0,0.0,51103.0,10512.0,74.0,0.0,0.0,144.0,147.0,43.0,29.0,6.0,43.0,NaN,NaN,NaN,0.0,3.0,4.0,3.0,7.0,8.0,4.0,13.0,4.0,7.0,0.0,0.0,0.0,0.0,100.0,33.3,0.0,0.0,402391.0,40723.0,40500.0,15582.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2260665,89937139,NaN,40000.0,40000.0,39925.0,60 months,13.49,920.19,C,C2,Director of Distribution,10+ years,MORTGAGE,200000.0,Verified,Oct-2016,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=89937139,NaN,debt_consolidation,Debt consolidation,270xx,NC,31.22,0.0,Nov-1983,710.0,714.0,0.0,NaN,NaN,17.0,0.0,125186.0,81.1,24.0,f,23973.21,23928.26,26610.570000,26560.68,16026.79,10583.78,0.0,0.0,0.000,Mar-2019,920.19,Apr-2019,Mar-2019,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,513402.0,0.0,3.0,1.0,1.0,7.0,26015.0,46.0,1.0,4.0,33587.0,59.0,138400.0,0.0,5.0,1.0,6.0,32088.0,3730.0,63.1,0.0,0.0,104.0,193.0,11.0,7.0,2.0,51.0,NaN,12.0,NaN,0.0,4.0,10.0,5.0,5.0,5.0,11.0,15.0,10.0,17.0,0.0,0.0,0.0,2.0,100.0,50.0,0.0,0.0,595565.0,180207.0,43000.0,56557.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260676,90041095,NaN,32000.0,32000.0,31950.0,60 months,14.49,752.74,C,C4,Manager,10+ years,MORTGAGE,98000.0,Verified,Oct-2016,Current,n,https://lendingclub.com/browse/loanDetail.action?loan_id=90041095,NaN,debt_consolidation,Debt consolidation,956xx,CA,3.43,0.0,Mar-2003,665.0,669.0,0.0,NaN,72.0,6.0,1.0,8094.0,74.9,25.0,f,19368.71,19338.45,21765.060000,21731.05,12631.29,9133.77,0.0,0.0,0.000,Mar-2019,752.74,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,239243.0,1.0,0.0,1.0,2.0,12.0,0.0,NaN,2.0,2.0,5334.0,75.0,10800.0,0.0,1.0,0.0,4.0,39874.0,429.0,94.8,0.0,0.0,99.0,156.0,3.0,3.0,3.0,34.0,NaN,NaN,NaN,0.0,3.0,4.0,3.0,9.0,5.0,5.0,16.0,4.0,6.0,0.0,0.0,0.0,3.0,100.0,100.0,1.0,0.0,312351.0,8094.0,8300.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260680,89024450,NaN,40000.0,40000.0,39975.0,60 months,15.59,964.03,C,C5,Sr. Project Manager,< 1 year,MORTGAGE,220000.0,Verified,Oct-2016,Fully Paid,n,https://lendingclub.com/browse/loanDetail.action?loan_id=89024450,NaN,debt_consolidation,Debt consolidation,114xx,NY,10.88,0.0,Feb-2004,715.0,719.0,2.0,NaN,NaN,19.0,0.0,43437.0,13.3,45.0,f,0.00,0.00,42089.416411,42063.11,40000.00,2089.42,0.0,0.0,0.000,Feb-2017,39283.94,NaN,Mar-2019,779.0,775.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,394526.0,2.0,3.0,1.0,3.0,9.0,29395.0,83.0,1.0,3.0,24661.0,27.0,185700.0,1.0,5.0,3.0,7.0,20765.0,107774.0,8.9,0.0,0.0,104.0,151.0,2.0,2.0,4.0,16.0,NaN,2.0,NaN,0.0,5.0,8.0,9.0,13.0,12.0,14.0,28.0,8.0,19.0,0.0,0.0,0.0,3.0,100.0,0.0,0.0,0.0,558214.0,73480.0,141000.0,35551.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [21]:
#Range of differences really varied from small amounts to large amounts.....

print(len(sorted(inv_funded.funded_amnt - inv_funded.funded_amnt_inv, reverse=True)))
sorted(inv_funded.funded_amnt - inv_funded.funded_amnt_inv, reverse=True)

151111

[32474.996080527366,
 30550.0,
 30375.0,
 28925.0,
 28803.30449373803,
 28675.0,
 27825.0,
 26025.0,
 25000.0,
 24925.012476049884,
 24897.43,
 24725.00801065504,
 24699.99482640253,
 24675.0,
 24625.0,
 24549.995571686533,
 24536.34,
 24525.00053112724,
 24500.000598948987,
 24475.0,
 24400.0,
 24324.9936925794,
 24249.99968865718,
 23925.0,
 23875.0,
 23849.9960690462,
 23800.0,
 23725.002896446527,
 23725.0,
 23711.73484796421,
 23707.72,
 23600.0,
 23600.0,
 23290.85,
 23275.0,
 23250.0,
 23249.99464166951,
 23100.0,
 23099.996015299384,
 23097.42,
 23031.832617572185,
 23025.0,
 23000.000164277353,
 22975.0,
 22956.53,
 22925.0,
 22900.0,
 22850.0,
 22775.0,
 22769.34,
 22574.99442342763,
 22550.0,
 22549.997200802296,
 22450.0,
 22449.990287067794,
 22425.00191101816,
 22403.17,
 22349.99743048092,
 22288.82165524837,
 22206.80776126677,
 22200.0,
 22150.0,
 22002.86,
 21863.871338593624,
 21836.828458006014,
 21725.003030860684,
 21677.47,
 21675.001129763703,
 21650.00677643939,
 21571.211700283748,
 21475.0,
 21425.0,
 21349.98969011377,
 21275.00974090936,
 21175.00622594708,
 21174.99981512027,
 21124.994133802444,
 21000.0,
 20950.0,
 20925.00527722868,
 20675.003358437887,
 20674.995303792624,
 20575.00403411614,
 20519.510000000002,
 20500.00026438744,
 20494.315209386667,
 20322.05776416569,
 20300.0,
 20130.453210716994,
 20119.56,
 20100.0,
 20100.0,
 20044.21,
 20025.009695560737,
 20025.0,
 20023.9,
 19950.0,
 19934.04351231925,
 19924.29,
 19884.69,
 19834.93169796947,
 19800.0,
 19775.0,
 19774.41280545903,
 19725.0,
 19725.0,
 19689.020998287677,
 19424.99813490698,
 19359.3,
 19300.0,
 19299.99608015417,
 19275.0,
 19214.249245546605,
 19200.0,
 19200.0,
 19150.002783050903,
 19150.0,
 19122.25,
 19071.62,
 19036.46,
 19025.0,
 19000.0,
 18968.111313132733,
 18950.00260309462,
 18935.274293278504,
 18900.0,
 18899.999497700614,
 18875.0,
 18850.0,
 18800.0,
 18749.994298346894,
 18674.99886491256,
 18639.56,
 18625.0,
 18600.0,
 18521.4,
 18489.87,
 18350.00549068387,
 18343.3,
 18325.0,
 18224.551305220666,
 18132.92,
 18125.0,
 18125.0,
 18113.462841234737,
 18075.0,
 18032.12889661181,
 18000.0,
 18000.0,
 17944.5,
 17933.94,
 17896.82,
 17881.78664096034,
 17874.99643292194,
 17850.0,
 17756.37423643414,
 17750.0,
 17725.000000000004,
 17724.99531704326,
 17700.0,
 17692.302426568203,
 17682.027880358655,
 17675.0,
 17650.0,
 17622.672946583472,
 17550.0,
 17525.0,
 17525.0,
 17475.0,
 17471.98,
 17434.71,
 17403.784575268663,
 17390.8,
 17375.0,
 17341.994987543636,
 17315.43731623697,
 17275.0,
 17200.000605302175,
 17200.0,
 17185.39,
 17175.0,
 17150.0,
 17100.0,
 17097.03,
 17050.0,
 17024.99543372458,
 16975.0,
 16950.006270217746,
 16950.0,
 16876.45,
 16808.56962860982,
 16800.0,
 16798.98443106805,
 16700.0,
 16700.0,
 16700.0,
 16699.986299565102,
 16697.54,
 16600.0,
 16575.0,
 16524.999545231323,
 16515.957594177366,
 16514.44,
 16375.0,
 16325.00345756276,
 16257.72,
 16225.545835153884,
 16225.0,
 16150.001183790584,
 16150.0,
 16100.003609930065,
 16100.0,
 16067.888474021951,
 16066.4,
 16025.0,
 16000.002103692656,
 15975.0,
 15968.70948603891,
 15949.998451557927,
 15925.0,
 15924.994727103998,
 15900.0,
 15899.995847256534,
 15889.751619986984,
 15825.0,
 15814.997300115385,
 15786.276699415923,
 15775.0,
 15774.9988329866,
 15750.0,
 15739.87845497362,
 15732.325187949824,
 15725.0,
 15675.002661429744,
 15668.418933752037,
 15650.0,
 15649.997047474008,
 15625.0,
 15600.002165574984,
 15599.997851318778,
 15575.008308213417,
 15575.0,
 15574.998495574351,
 15550.0,
 15524.986261896414,
 15475.0,
 15464.0,
 15425.000144009093,
 15424.996560423375,
 15407.916261576771,
 15393.266803767956,
 15380.611934072314,
 15350.0,
 15325.0,
 15275.567840006772,
 15274.999999999998,
 15274.997173734171,
 15250.00085174204,
 15219.54,
 15200.0,
 15199.993724917473,
 15167.651509188505,
 15150.0,
 15150.0,
 15050.004751670243,
 15050.003024680522,
 15047.781721826128,
 15030.904586717072,
 15000.00703980257,
 15000.004352137506,
 15000.0,
 15000.0,
 15000.0,
 15000.0,
 14999.999755065684,
 14999.994866930068,
 14961.887368485442,
 14900.0,
 14850.0,
 14800.0,
 14775.0,
 14732.219902194665,
 14725.0,
 14722.31,
 14700.0,
 14679.65,
 14650.0,
 14650.0,
 14649.992981796478,
 14647.222382884851,
 14625.002216491805,
 14620.82,
 14614.67,
 14575.0,
 14550.0,
 14541.782743872467,
 14499.349127719073,
 14475.0,
 14450.001137208648,
 14450.0,
 14450.0,
 14449.994216472429,
 14425.0,
 14425.0,
 14415.48,
 14375.0,
 14350.0,
 14325.0,
 14325.0,
 14300.001948632738,
 14286.058543646559,
 14275.005254138769,
 14250.005412239727,
 14241.27561629842,
 14224.995084196358,
 14200.0,
 14200.0,
 14175.010397671515,
 14175.0,
 14172.69,
 14170.58,
 14150.0,
 14115.619999999999,
 14108.32,
 14100.0,
 14099.99399056509,
 14036.210551302807,
 14025.00579327333,
 14025.0,
 14025.0,
 14024.99593239609,
 14022.29,
 14000.0,
 13931.67064720664,
 13925.0,
 13900.0,
 13900.0,
 13875.000573902023,
 13854.91,
 13824.993792429912,
 13822.01,
 13800.0,
 13775.24,
 13771.609237169809,
 13750.0,
 13725.0,
 13722.46,
 13722.29,
 13710.484436851631,
 13700.0,
 13700.0,
 13699.9,
 13688.176793006798,
 13675.0,
 13675.0,
 13674.994326363601,
 13625.0,
 13575.0,
 13550.883973631857,
 13550.0,
 13549.996456825198,
 13517.538628739567,
 13506.424605006241,
 13499.999548197567,
 13499.42318828963,
 13450.0,
 13450.0,
 13450.0,
 13449.996746227012,
 13425.0,
 13404.2,
 13400.0,
 13399.990734353565,
 13399.983852031113,
 13375.0,
 13374.993349452401,
 13360.05,
 13353.117371561146,
 13334.866771225945,
 13300.0,
 13300.0,
 13275.0,
 13179.019418724803,
 13175.005849670988,
 13163.27,
 13150.0,
 13138.419947949656,
 13125.0,
 13124.999394916977,
 13117.935622630048,
 13105.110973188406,
 13100.0,
 13075.0,
 13075.0,
 13050.001421667475,
 13050.0,
 13049.17,
 13009.33,
 13000.869999999999,
 12976.351731241539,
 12975.0,
 12974.999550375123,
 12951.221839151403,
 12950.00085405832,
 12949.26,
 12927.114127531806,
 12925.0,
 12900.0055569619,
 12900.004634294382,
 12900.0,
 12889.31,
 12850.0,
 12850.0,
 12850.0,
 12821.65,
 12800.00127566228,
 12726.231788337753,
 12725.0045597399,
 12725.0,
 12711.209934411923,
 12700.0,
 12700.0,
 12675.006610237724,
 12674.991043128894,
 12656.546660695201,
 12650.0,
 12599.996834765374,
 12567.500058331989,
 12558.34,
 12549.996058640776,
 12525.0,
 12525.0,
 12503.159861667402,
 12500.0,
 12468.17518703288,
 12450.0,
 12450.0,
 12449.606398890219,
 12420.75,
 12399.998657730812,
 12375.0,
 12368.72,
 12325.0,
 12325.0,
 12325.0,
 12300.0,
 12300.0,
 12299.997906289562,
 12299.997667008616,
 12299.991314507184,
 12275.0,
 12250.002165432223,
 12250.0,
 12249.996330116917,
 12225.70600537353,
 12225.546972139471,
 12200.004408637808,
 12200.0,
 12191.72883311002,
 12181.19897283762,
 12175.0,
 12148.919,
 12145.31,
 12124.999079973291,
 12100.0,
 12100.0,
 12071.22,
 12066.55,
 12050.0,
 12034.430789863754,
 12032.643252233076,
 12025.0,
 12024.999809014364,
 12017.057524081876,
 12000.007240748271,
 12000.0,
 12000.0,
 11999.253000329987,
 11975.13,
 11950.000280224196,
 11950.0,
 11949.66,
 11890.21,
 11879.350146665955,
 11875.0,
 11850.0,
 11850.0,
 11850.0,
 11843.32,
 11832.451665236053,
 11825.000958125793,
 11815.7,
 11810.32,
 11802.599627347317,
 11800.0,
 11786.73,
 11775.0,
 11771.695392514906,
 11765.17,
 11757.298378920408,
 11750.005658610957,
 11750.003998700253,
 11750.0,
 11750.0,
 11725.005346036874,
 11725.0,
 11725.0,
 11724.991763720313,
 11718.466458355088,
 11700.33,
 11692.94,
 11640.298423124348,
 11636.991680018667,
 11625.007278255467,
 11625.0,
 11600.0,
 11600.0,
 11575.149085289264,
 11575.002047932827,
 11558.31,
 11545.300066372341,
 11544.47712545533,
 11525.008150219595,
 11525.0,
 11524.994792143061,
 11524.989996385935,
 11500.0,
 11455.75,
 11450.0,
 11449.997587159924,
 11447.08,
 11419.83,
 11417.410000000002,
 11400.0,
 11377.289357981412,
 11375.005815516699,
 11375.0,
 11356.085134288423,
 11343.31,
 11340.14,
 11325.0,
 11306.890705599886,
 11300.0,
 11300.0,
 11300.0,
 11298.533978539394,
 11275.44,
 11275.0,
 11233.04593489334,
 11225.0,
 11216.913335794714,
 11200.0,
 11187.300446445883,
 11177.929999999998,
 11150.0,
 11150.0,
 11132.969341218428,
 11126.758656068465,
 11125.0,
 11125.0,
 11124.999159191091,
 11100.0,
 11100.0,
 11097.36,
 11082.606632053574,
 11075.004908323765,
 11075.0,
 11062.629274351024,
 11057.17300407328,
 11055.453311413385,
 11050.0,
 11041.783458014024,
 11040.75,
 11025.000482950745,
 11025.0,
 11024.997926436266,
 11017.560000000001,
 11000.0,
 11000.0,
 10975.0,
 10975.0,
 10975.0,
 10975.0,
 10974.999770256756,
 10968.677363651434,
 10960.37932921076,
 10950.0,
 10920.62526467859,
 10900.0,
 10900.0,
 10897.893750776859,
 10892.9934993947,
 10877.322338881559,
 10875.0,
 10863.380000000001,
 10850.0,
 10848.938466718331,
 10825.0,
 10768.580720091722,
 10750.000110134975,
 10750.0,
 10746.01477190157,
 10729.405882656349,
 10725.0,
 10725.0,
 10676.250893786078,
 10650.0,
 10649.996004900957,
 10625.0,
 10624.997248981539,
 10597.34,
 10575.0,
 10558.33,
 10550.0,
 10549.999867718287,
 10499.95,
 10492.369529105303,
 10475.002541067834,
 10475.0,
 10475.0,
 10450.0,
 10449.99593853816,
 10442.981759548433,
 10427.619107527393,
 10425.0,
 10425.0,
 10424.99523098663,
 10406.17502779068,
 10386.086002211818,
 10385.97,
 10379.386638522648,
 10360.72,
 10342.88,
 10299.995145296327,
 10279.07,
 10275.0,
 10274.99403931637,
 10267.88,
 10266.05,
 10255.731173323282,
 10250.0,
 10239.446496913482,
 10225.0,
 10225.0,
 10225.0,
 10224.994333071327,
 10223.86,
 10200.0,
 10175.0,
 10157.179057177806,
 10125.0,
 10100.0,
 10100.0,
 10100.0,
 10100.0,
 10100.0,
 10075.0,
 10073.333322691024,
 10065.190817413655,
 10050.64,
 10050.0,
 10050.0,
 10049.998033025984,
 10035.814474181283,
 10025.0,
 10024.99738964527,
 10007.304548300159,
 10002.621595749006,
 10000.0,
 10000.0,
 10000.0,
 10000.0,
 10000.0,
 9999.991258125348,
 9986.035502195602,
 9962.2334776434,
 9950.82,
 9942.50055430439,
 9935.251658680523,
 9925.00171858392,
 9900.0,
 9900.0,
 9875.0,
 9875.0,
 9875.0,
 9850.005023754899,
 9849.993441203249,
 9825.796122268699,
 9825.0,
 9803.909343370691,
 9800.001151322373,
 9800.0,
 9800.0,
 9775.0,
 9775.0,
 9775.0,
 9775.0,
 9762.833298709813,
 9750.0,
 9750.0,
 9749.997363288592,
 9725.0,
 9683.060000000001,
 9669.267950109148,
 9663.28942158971,
 9650.000070930024,
 9650.0,
 9650.0,
 9650.0,
 9650.0,
 9633.06,
 9624.264678425412,
 9600.011619855368,
 9600.0,
 9596.645918094197,
 9576.201857322085,
 9575.0,
 9574.9960715167,
 9565.106509034395,
 9549.997221666385,
 9543.25,
 9539.22,
 9531.139363501705,
 9523.07,
 9517.281463500189,
 9500.001169819916,
 9500.0,
 9500.0,
 9500.0,
 9496.11,
 9477.683406207,
 9476.876034663888,
 9475.0,
 9475.0,
 9475.0,
 9471.884792735034,
 9453.985301209745,
 9450.0,
 9434.562248391729,
 9427.08,
 9425.0,
 9425.0,
 9425.0,
 9400.0,
 9396.55,
 9375.0,
 9375.0,
 9375.0,
 9375.0,
 9375.0,
 9369.5,
 9352.939905790496,
 9325.617299203215,
 9325.0,
 9325.0,
 9325.0,
 9311.204767508316,
 9300.0,
 9272.617558009086,
 9250.0,
 9250.0,
 9246.856150981213,
 9225.002336143845,
 9225.0,
 9224.996025645873,
 9224.995590296086,
 9210.886892565828,
 9200.00567410011,
 9200.0,
 9200.0,
 9199.997891000214,
 9199.991759175504,
 9194.493612649869,
 9191.13140201346,
 9184.091615612344,
 9175.0,
 9175.0,
 9169.718679011816,
 9150.0,
 9142.073007782375,
 9140.28,
 9101.711127405015,
 9101.689999999999,
 9100.005744178605,
 9100.0,
 9096.529650352997,
 9094.705449501253,
 9094.33,
 9082.83,
 9075.542919650514,
 9075.0,
 9075.0,
 9050.0,
 9049.999007036029,
 9042.9337290312,
 9031.265647636365,
 9025.0,
 9025.0,
 9025.0,
 9025.0,
 9025.0,
 9014.68,
 9000.0,
 8975.0,
 8975.0,
 8964.747593417771,
 8964.300620004207,
 8958.86190362634,
 8949.996404203523,
 8949.995755036321,
 8949.130000000001,
 8939.67,
 8925.0,
 8908.24,
 8900.0,
 8900.0,
 8900.0,
 8899.997081105954,
 8875.0,
 8875.0,
 8862.279999999999,
 8850.001455882351,
 8847.29,
 8825.005117081097,
 8821.869999999999,
 8814.39,
 8810.94,
 8804.72,
 8800.0,
 8800.0,
 8775.0,
 8771.94,
 8768.318966348155,
 8754.530037014498,
 8750.0,
 8750.0,
 8750.0,
 8733.511610302314,
 8724.996891931742,
 8678.9,
 8678.782151663074,
 8677.316615746771,
 8675.004649653605,
 8675.001359378926,
 8675.0,
 8675.0,
 8667.466149604767,
 8652.64,
 8650.0,
 8650.0,
 8649.997599607475,
 8649.49,
 8625.002763100816,
 8625.0,
 8602.1,
 8599.994441059058,
 8575.004436764228,
 8575.0,
 8575.0,
 8571.064266656254,
 8559.454728676978,
 8550.002684668832,
 8550.0,
 8550.0,
 8534.95137158436,
 8523.47,
 8500.0,
 8499.998539714486,
 8475.0,
 8475.0,
 8474.996160279767,
 8471.619999999999,
 8450.0,
 8449.9983400296,
 8437.579965747806,
 8425.0,
 8425.0,
 8425.0,
 8418.382380212784,
 8400.009068123789,
 8400.0,
 8388.139390339971,
 8383.3,
 8368.45,
 8352.248640122201,
 8350.0,
 8346.9464315851,
 8334.07,
 8326.84,
 8325.0,
 8325.0,
 8314.16,
 8314.131374376433,
 8308.66642622999,
 8308.504572790032,
 8300.0,
 8285.11,
 8275.0,
 8274.995008748334,
 8266.343568206525,
 8265.297112248216,
 8261.511128274542,
 8250.001419030168,
 8243.840822911061,
 8241.52,
 8239.47,
 8235.819043574851,
 8225.001767358568,
 8225.0,
 8225.0,
 8225.0,
 8224.99732379425,
 8203.730954516672,
 8202.817460880073,
 8200.0,
 8200.0,
 8187.32,
 8185.2,
 8176.92,
 8174.995262266861,
 8151.295999132787,
 8143.85,
 8136.993098059215,
 8128.800062842564,
 8125.0,
 8125.0,
 8125.0,
 8124.996595460869,
 8123.13,
 8110.07,
 8108.2606775062795,
 8100.000336096467,
 8100.0,
 8094.161591435275,
 8084.118465748508,
 8075.0,
 8074.999417138807,
 8070.439273594529,
 8067.925498182616,
 8065.55453096012,
 8054.04724340877,
 8050.0,
 8050.0,
 8050.0,
 8048.50447433198,
 8026.67953992934,
 8025.583885945059,
 8025.0,
 8025.0,
 8025.0,
 8025.0,
 8024.490000000002,
 8015.976161354628,
 8007.891352396517,
 8003.435609494913,
 8001.61,
 8000.000416412788,
 8000.0,
 7999.99999812424,
 7999.99648572203,
 7999.993138366279,
 7999.594685287762,
 7995.26,
 7975.833658631134,
 7975.0,
 7975.0,
 7975.0,
 7952.15,
 7950.0,
 7950.0,
 7949.998809229495,
 7948.85,
 7937.840110585901,
 7925.0,
 7903.397952609392,
 7902.951410958244,
 7900.0,
 7900.0,
 7899.992406789271,
 7875.0,
 7875.0,
 7875.0,
 7873.99,
 7850.0,
 7850.0,
 7850.0,
 7850.0,
 7849.991688607171,
 7844.85,
 7836.841242396917,
 7834.893463088136,
 7834.206564337688,
 7832.80154833125,
 7825.821046748088,
 7825.0,
 7825.0,
 7800.0,
 7800.0,
 7800.0,
 7800.0,
 ...]

In [22]:
#There are 233 observations where investor funded amount was 0, but loan was still funded. 
a[a.funded_amnt_inv == 0].shape

(233, 152)

In [23]:
#5. Categorize features as known, unknown, not_important, not_sure at time of loan:

In [24]:
not_important = ['id', 'member_id']

In [25]:
not_sure = ['loan_amnt', 'funded_amnt_inv']  #Can experiment later after we have baseline model

In [26]:
known = ['funded_amnt', 'term', 'int_rate', 'installment', 'grade', 
         'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
         'purpose', 'title', 'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_low', 'fico_range_high',
         'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record', 'open_acc', 'pub_rec',
         'total_acc', 'initial_list_status']

In [27]:
len(known)

25

In [28]:
#Start with top 10 + Label to create baseline:

top_10 = ['funded_amnt', 'term', 'int_rate', 'installment', 'grade',
          'emp_length', 'annual_inc', 'verification_status',
          'dti', 'fico_range_low', 'loan_status_bin']

In [29]:
len(top_10)

11

In [30]:
#6. Inspect Dataframe with Top Features (10 to start):

In [61]:
df = a[top_10]
df

,funded_amnt,term,int_rate,installment,grade,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin
0,3600.0,36 months,13.99,123.03,C,10+ years,55000.0,Not Verified,5.91,675.0,0.0
1,24700.0,36 months,11.99,820.28,C,10+ years,65000.0,Not Verified,16.06,715.0,0.0
2,20000.0,60 months,10.78,432.66,B,10+ years,63000.0,Not Verified,10.78,695.0,0.0
3,35000.0,60 months,14.85,829.90,C,10+ years,110000.0,Source Verified,17.06,785.0,NaN
4,10400.0,60 months,22.45,289.91,F,3 years,104433.0,Source Verified,25.37,695.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2260694,24000.0,60 months,12.79,543.50,C,7 years,95000.0,Source Verified,19.61,665.0,NaN
2260695,24000.0,60 months,10.49,515.74,B,10+ years,108000.0,Not Verified,34.94,695.0,NaN
2260696,40000.0,60 months,10.49,859.56,B,9 years,227000.0,Verified,12.75,705.0,NaN
2260697,24000.0,60 months,14.49,564.56,C,6 years,110000.0,Not Verified,18.30,660.0,1.0
2260698,14000.0,60 months,14.49,329.33,C,10+ years,95000.0,Verified,23.36,660.0,NaN

In [62]:
df.isna().sum()

funded_amnt                 0
term                        0
int_rate                    0
installment                 0
grade                       0
emp_length             146907
annual_inc                  4
verification_status         0
dti                      1711
fico_range_low              0
loan_status_bin        915358
dtype: int64

In [63]:
df = df[~df.loan_status_bin.isna()]
df

,funded_amnt,term,int_rate,installment,grade,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin
0,3600.0,36 months,13.99,123.03,C,10+ years,55000.0,Not Verified,5.91,675.0,0.0
1,24700.0,36 months,11.99,820.28,C,10+ years,65000.0,Not Verified,16.06,715.0,0.0
2,20000.0,60 months,10.78,432.66,B,10+ years,63000.0,Not Verified,10.78,695.0,0.0
4,10400.0,60 months,22.45,289.91,F,3 years,104433.0,Source Verified,25.37,695.0,0.0
5,11950.0,36 months,13.44,405.18,C,4 years,34000.0,Source Verified,10.20,690.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2260688,18000.0,60 months,9.49,377.95,B,5 years,130000.0,Not Verified,20.59,735.0,0.0
2260690,29400.0,60 months,13.99,683.94,C,9 years,180792.0,Not Verified,22.03,705.0,0.0
2260691,32000.0,60 months,14.49,752.74,C,3 years,157000.0,Source Verified,10.34,735.0,1.0
2260692,16000.0,60 months,12.79,362.34,C,10+ years,150000.0,Not Verified,12.25,665.0,0.0
2260697,24000.0,60 months,14.49,564.56,C,6 years,110000.0,Not Verified,18.30,660.0,1.0

In [64]:
df.isna().sum()

funded_amnt                0
term                       0
int_rate                   0
installment                0
grade                      0
emp_length             78511
annual_inc                 0
verification_status        0
dti                      374
fico_range_low             0
loan_status_bin            0
dtype: int64

In [65]:
df = df.dropna()
df

,funded_amnt,term,int_rate,installment,grade,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin
0,3600.0,36 months,13.99,123.03,C,10+ years,55000.0,Not Verified,5.91,675.0,0.0
1,24700.0,36 months,11.99,820.28,C,10+ years,65000.0,Not Verified,16.06,715.0,0.0
2,20000.0,60 months,10.78,432.66,B,10+ years,63000.0,Not Verified,10.78,695.0,0.0
4,10400.0,60 months,22.45,289.91,F,3 years,104433.0,Source Verified,25.37,695.0,0.0
5,11950.0,36 months,13.44,405.18,C,4 years,34000.0,Source Verified,10.20,690.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2260688,18000.0,60 months,9.49,377.95,B,5 years,130000.0,Not Verified,20.59,735.0,0.0
2260690,29400.0,60 months,13.99,683.94,C,9 years,180792.0,Not Verified,22.03,705.0,0.0
2260691,32000.0,60 months,14.49,752.74,C,3 years,157000.0,Source Verified,10.34,735.0,1.0
2260692,16000.0,60 months,12.79,362.34,C,10+ years,150000.0,Not Verified,12.25,665.0,0.0
2260697,24000.0,60 months,14.49,564.56,C,6 years,110000.0,Not Verified,18.30,660.0,1.0

In [66]:
df.loan_status_bin.value_counts()

0.0    1019356
1.0     247426
Name: loan_status_bin, dtype: int64

In [67]:
df.dtypes

funded_amnt            float64
term                    object
int_rate               float64
installment            float64
grade                   object
emp_length              object
annual_inc             float64
verification_status     object
dti                    float64
fico_range_low         float64
loan_status_bin        float64
dtype: object

In [68]:
#Return unique values of categorical columns:
{column: list(df[column].unique()) for column in df.columns if df.dtypes[column]=='object'}

{'term': [' 36 months', ' 60 months'],
 'grade': ['C', 'B', 'F', 'A', 'E', 'D', 'G'],
 'emp_length': ['10+ years',
  '3 years',
  '4 years',
  '6 years',
  '7 years',
  '8 years',
  '2 years',
  '5 years',
  '9 years',
  '< 1 year',
  '1 year'],
 'verification_status': ['Not Verified', 'Source Verified', 'Verified']}

In [69]:
sorted(df['grade'].unique())

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [70]:
sorted(df['emp_length'].unique())

['1 year',
 '10+ years',
 '2 years',
 '3 years',
 '4 years',
 '5 years',
 '6 years',
 '7 years',
 '8 years',
 '9 years',
 '< 1 year']

In [71]:
target = 'loan_status_bin'

binary_features = ['term']
binary_positives = [' 60 months']      #indicate which value == 1

ordinal_features = ['emp_length', 'grade']
emp_ordering = [
    '< 1 year',
    '1 year',
    '2 years',
    '3 years',
    '4 years',
    '5 years',
    '6 years',
    '7 years',
    '8 years',
    '9 years',
    '10+ years',
    ]
grade_ordering = ['A', 'B', 'C', 'D', 'E', 'F', 'G']

nominal_features = ['verification status']

In [97]:
#Encoding Functions

def binary_temp(df, column, positive_value):
    temp_df = df.assign(new_be=df[column].apply(lambda x: 1 if x == positive_value else 0))
    return temp_df

def binary_encode(temp_df, column):
    new_df = temp_df.drop(column, axis=1)
    new_df = new_df.rename(columns={'new_be':column})
    return new_df
    
    #df[column + '_be'] = df[column].apply(lambda x: 1 if x == positive_value else 0)
    #df_new = pd.concat([df, df[column].apply(lambda x: 1 if x == positive_value else 0)], axis=1)
    #df_new = df_new.drop(column, axis=1)
    #return df_new

def ordinal_temp(df, column, ordering):
    temp_df = df.assign(new_oe=df[column].apply(lambda x: ordering.index(x)))
    return temp_df

def ordinal_encode(temp_df, column):
    new_df = temp_df.drop(column, axis=1)
    new_df = new_df.rename(columns={'new_oe':column})
    return new_df

def onehot_encode(df, column):
    dummies = pd.get_dummies(df[column])
    df_new = pd.concat([df, dummies], axis=1)
    df_new = df_new.drop(column, axis=1)
    return df_new

In [98]:
#list(zip(binary_features, binary_positives))

In [99]:
#Check Binary Encoding:

temp = binary_temp(df, 'term', ' 60 months')

#for feature, positive_value in zip(binary_features, binary_positives):
#    df2 = binary_encode(df, feature, positive_value)

In [100]:
temp[['term', 'new_be']].sample(10)

               term  new_be
1914900   36 months       0
1895968   36 months       0
1218126   60 months       1
1822856   36 months       0
1866150   36 months       0
1272894   60 months       1
1041838   60 months       1
1207262   36 months       0
1134538   36 months       0
636099    36 months       0

In [101]:
temp.head(5)

,funded_amnt,term,int_rate,installment,grade,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin,new_be
0,3600.0,36 months,13.99,123.03,C,10+ years,55000.0,Not Verified,5.91,675.0,0.0,0
1,24700.0,36 months,11.99,820.28,C,10+ years,65000.0,Not Verified,16.06,715.0,0.0,0
2,20000.0,60 months,10.78,432.66,B,10+ years,63000.0,Not Verified,10.78,695.0,0.0,1
4,10400.0,60 months,22.45,289.91,F,3 years,104433.0,Source Verified,25.37,695.0,0.0,1
5,11950.0,36 months,13.44,405.18,C,4 years,34000.0,Source Verified,10.20,690.0,0.0,0

In [102]:
#If ok, complete binary encoding:
new_df = binary_encode(temp, 'term')
new_df.head(5)

,funded_amnt,int_rate,installment,grade,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin,term
0,3600.0,13.99,123.03,C,10+ years,55000.0,Not Verified,5.91,675.0,0.0,0
1,24700.0,11.99,820.28,C,10+ years,65000.0,Not Verified,16.06,715.0,0.0,0
2,20000.0,10.78,432.66,B,10+ years,63000.0,Not Verified,10.78,695.0,0.0,1
4,10400.0,22.45,289.91,F,3 years,104433.0,Source Verified,25.37,695.0,0.0,1
5,11950.0,13.44,405.18,C,4 years,34000.0,Source Verified,10.20,690.0,0.0,0

In [103]:
#Check Ordinal Encoding:
temp = ordinal_temp(new_df, 'grade', grade_ordering)

In [104]:
temp.sample(10)

,funded_amnt,int_rate,installment,grade,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin,term,new_oe
14967,15000.0,13.67,510.27,C,10+ years,68000.0,Verified,30.96,690.0,1.0,0,2
1903627,16000.0,14.09,547.55,B,10+ years,115000.0,Not Verified,5.90,705.0,0.0,0,1
17889,35000.0,9.76,1125.42,B,4 years,120000.0,Source Verified,24.92,750.0,0.0,0,1
1734901,7000.0,11.39,230.47,B,10+ years,65000.0,Verified,12.85,660.0,1.0,0,1
59463,7000.0,7.26,216.98,A,10+ years,86400.0,Source Verified,11.42,690.0,0.0,0,0
402520,7000.0,12.39,233.81,C,7 years,28000.0,Not Verified,23.41,680.0,0.0,0,2
568988,2000.0,11.99,66.42,B,10+ years,35000.0,Not Verified,7.03,675.0,0.0,0,1
1923416,5375.0,13.11,181.39,B,3 years,60000.0,Not Verified,26.36,680.0,0.0,0,1
1662002,20000.0,10.49,649.96,B,2 years,95000.0,Not Verified,7.28,710.0,0.0,0,1
1967682,20000.0,22.39,556.83,E,2 years,93600.0,Verified,13.81,700.0,0.0,1,4

In [105]:
temp.head(5)

,funded_amnt,int_rate,installment,grade,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin,term,new_oe
0,3600.0,13.99,123.03,C,10+ years,55000.0,Not Verified,5.91,675.0,0.0,0,2
1,24700.0,11.99,820.28,C,10+ years,65000.0,Not Verified,16.06,715.0,0.0,0,2
2,20000.0,10.78,432.66,B,10+ years,63000.0,Not Verified,10.78,695.0,0.0,1,1
4,10400.0,22.45,289.91,F,3 years,104433.0,Source Verified,25.37,695.0,0.0,1,5
5,11950.0,13.44,405.18,C,4 years,34000.0,Source Verified,10.20,690.0,0.0,0,2

In [106]:
new_df = ordinal_encode(temp, 'grade')
new_df.head(5)

,funded_amnt,int_rate,installment,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin,term,grade
0,3600.0,13.99,123.03,10+ years,55000.0,Not Verified,5.91,675.0,0.0,0,2
1,24700.0,11.99,820.28,10+ years,65000.0,Not Verified,16.06,715.0,0.0,0,2
2,20000.0,10.78,432.66,10+ years,63000.0,Not Verified,10.78,695.0,0.0,1,1
4,10400.0,22.45,289.91,3 years,104433.0,Source Verified,25.37,695.0,0.0,1,5
5,11950.0,13.44,405.18,4 years,34000.0,Source Verified,10.20,690.0,0.0,0,2

In [109]:
#Check Ordinal Encoding:
temp = ordinal_temp(new_df, 'emp_length', emp_ordering)

In [111]:
temp.sample(10)

,funded_amnt,int_rate,installment,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin,term,grade,new_oe
1792277,8400.0,20.20,313.04,3 years,35000.0,Verified,24.27,660.0,0.0,0,3,3
1080350,23650.0,10.75,771.48,2 years,67500.0,Not Verified,27.18,730.0,0.0,0,1,2
373356,8300.0,12.69,278.43,2 years,40000.0,Verified,18.96,680.0,0.0,0,2,2
161640,15000.0,13.99,348.95,9 years,52000.0,Not Verified,13.85,670.0,0.0,1,2,9
1993937,3200.0,7.99,100.27,1 year,41000.0,Source Verified,7.23,755.0,1.0,0,0,1
242612,7000.0,9.17,223.16,10+ years,72000.0,Not Verified,21.65,685.0,1.0,0,1,10
1718993,35000.0,17.99,1265.16,2 years,123000.0,Source Verified,5.43,675.0,0.0,0,3,2
650173,12000.0,7.07,370.91,1 year,60000.0,Verified,5.33,750.0,0.0,0,0,1
1294586,19500.0,13.65,450.21,5 years,65000.0,Not Verified,16.59,710.0,0.0,1,2,5
1163787,13000.0,14.99,450.59,10+ years,75000.0,Not Verified,18.61,665.0,0.0,0,2,10

In [112]:
temp.head(3)

,funded_amnt,int_rate,installment,emp_length,annual_inc,verification_status,dti,fico_range_low,loan_status_bin,term,grade,new_oe
0,3600.0,13.99,123.03,10+ years,55000.0,Not Verified,5.91,675.0,0.0,0,2,10
1,24700.0,11.99,820.28,10+ years,65000.0,Not Verified,16.06,715.0,0.0,0,2,10
2,20000.0,10.78,432.66,10+ years,63000.0,Not Verified,10.78,695.0,0.0,1,1,10

In [117]:
new_df = ordinal_encode(temp, 'emp_length')
new_df.head(3)

,funded_amnt,int_rate,installment,annual_inc,verification_status,dti,fico_range_low,loan_status_bin,term,grade,emp_length
0,3600.0,13.99,123.03,55000.0,Not Verified,5.91,675.0,0.0,0,2,10
1,24700.0,11.99,820.28,65000.0,Not Verified,16.06,715.0,0.0,0,2,10
2,20000.0,10.78,432.66,63000.0,Not Verified,10.78,695.0,0.0,1,1,10

In [124]:
#Dummify nominal features:
numerical_df = onehot_encode(new_df, 'verification_status')

In [125]:
#Check
numerical_df.sample(10)

,funded_amnt,int_rate,installment,annual_inc,dti,fico_range_low,loan_status_bin,term,grade,emp_length,Not Verified,Source Verified,Verified
1698076,14400.0,14.99,342.50,60000.0,6.98,675.0,0.0,1,2,10,0,0,1
1827096,9750.0,10.64,317.55,58000.0,13.66,740.0,0.0,0,1,1,0,0,1
1985921,2500.0,13.49,84.83,85000.0,7.54,660.0,0.0,0,2,10,1,0,0
361985,12000.0,9.99,387.15,60000.0,12.66,660.0,0.0,0,1,10,0,1,0
1143349,10000.0,10.49,324.98,129000.0,11.14,695.0,0.0,0,1,1,0,1,0
1773853,23000.0,6.03,700.02,100000.0,19.09,790.0,0.0,0,0,0,0,0,1
1115540,20000.0,6.99,617.46,76140.0,33.07,700.0,0.0,0,0,0,0,1,0
392800,12000.0,12.99,272.98,66500.0,21.55,725.0,0.0,1,2,10,0,1,0
575231,10000.0,7.97,313.23,63000.0,17.98,755.0,0.0,0,0,10,0,1,0
1210076,12750.0,13.98,435.65,43500.0,31.94,705.0,0.0,0,2,5,0,1,0

In [126]:
#Shape should change, check:
numerical_df.shape

(1266782, 13)

In [128]:
numerical_df.head(3)

,funded_amnt,int_rate,installment,annual_inc,dti,fico_range_low,loan_status_bin,term,grade,emp_length,Not Verified,Source Verified,Verified
0,3600.0,13.99,123.03,55000.0,5.91,675.0,0.0,0,2,10,1,0,0
1,24700.0,11.99,820.28,65000.0,16.06,715.0,0.0,0,2,10,1,0,0
2,20000.0,10.78,432.66,63000.0,10.78,695.0,0.0,1,1,10,1,0,0

In [129]:
#Cross-check all data types are now numerical, then you are ready to apply ML: 
numerical_df.dtypes

funded_amnt        float64
int_rate           float64
installment        float64
annual_inc         float64
dti                float64
fico_range_low     float64
loan_status_bin    float64
term                 int64
grade                int64
emp_length           int64
Not Verified         uint8
Source Verified      uint8
Verified             uint8
dtype: object

In [130]:
#Convert numerical dataframe to csv for ML:
numerical_df.to_csv('Ten.csv', index=False)